$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 2: Obst (40 items)
$b2 = @(
  @{ name="Kumquat"; kategorie="Obst"; saison=@("Winter"); aromaprofil=@("süß-sauer","zitrisch","aromatisch"); herkunft="China"; geschmack=@{acidity=4;sweetness=3;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Ente","Ingwer","Schokolade","Vanille"); beschreibung="Mini-Zitrusfrucht, bei der die Schale süß und das Fruchtfleisch sauer ist."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Pomelo"; kategorie="Obst"; saison=@("Winter","Frühling"); aromaprofil=@("mild-süß","blumig","bitter"); herkunft="Südostasien"; geschmack=@{acidity=2;sweetness=3;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Garnelen","Minze","Koriander","Ingwer"); beschreibung="Größte Zitrusfrucht mit milder Bitterkeit und blumiger Süße."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Lychee"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("blumig","süß","rosenähnlich"); herkunft="China"; geschmack=@{acidity=2;sweetness=5;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Himbeere","Rose","Champagner","Ingwer"); beschreibung="Exotische Tropenfrucht mit intensiv blumiger Süße und rosenähnlichem Duft."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Rambutan"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("süß","leicht säuerlich","tropisch"); herkunft="Südostasien"; geschmack=@{acidity=2;sweetness=4;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Kokosmilch","Limette","Ingwer","Chili"); beschreibung="Behaarte Tropenfrucht mit saftigem, süßem Fruchtfleisch und lycheeähnlichem Aroma."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Mangosteen"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("blumig","süß","zitrisch"); herkunft="Südostasien"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Vanille","Kokos","Mango","Joghurt"); beschreibung="Als 'Königin der Früchte' gilt sie wegen ihres einzigartigen Aromas."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Drachenfrucht"; kategorie="Obst"; saison=@("Sommer","Herbst"); aromaprofil=@("mild","leicht süß","neutral"); herkunft="Mittelamerika/Asien"; geschmack=@{acidity=1;sweetness=3;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Limette","Kokos","Mango","Passionsfrucht"); beschreibung="Tropenfrucht mit beeindruckender Optik, mildem Geschmack und leuchtend pinkfarbenem Fleisch."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Karambole"; kategorie="Obst"; saison=@("Herbst","Winter"); aromaprofil=@("leicht säuerlich","frisch","mild"); herkunft="Südostasien"; geschmack=@{acidity=3;sweetness=2;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Garnelen","Ingwer","Limette","Minze"); beschreibung="Sternförmige Tropenfrucht mit knackiger Textur und frisch-säuerlichem Geschmack."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Physalis"; kategorie="Obst"; saison=@("Herbst","Winter"); aromaprofil=@("süß-sauer","tropisch","aromatisch"); herkunft="Südamerika"; geschmack=@{acidity=3;sweetness=3;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Schokolade","Vanille","Sahne","Himbeere"); beschreibung="Goldene Beere in Lampionhülle mit intensivem süß-saurem Aroma."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Kaki"; kategorie="Obst"; saison=@("Herbst","Winter"); aromaprofil=@("süß","honigig","tannisch"); herkunft="Japan/China"; geschmack=@{acidity=1;sweetness=5;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Prosciutto","Burrata","Walnuss","Zimt"); beschreibung="Persimone mit tiefer, honigartiger Süße – die reife Fuyu-Sorte knackig, Hachiya weich."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Cherimoya"; kategorie="Obst"; saison=@("Winter"); aromaprofil=@("süß","creme-artig","tropisch"); herkunft="Andenregion"; geschmack=@{acidity=1;sweetness=5;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Zitrusfrüchte","Vanille","Kokos","Ingwer"); beschreibung="Von Mark Twain als 'köstlichste Frucht der Welt' bezeichnet – cremig und süß."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Guave"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("süß","tropisch","aromatisch","moschusartig"); herkunft="Mittelamerika"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Zitrusfrüchte","Ingwer","Kokos","Chili"); beschreibung="Intensiv aromatische Tropenfrucht mit rosafarbenem Fleisch und blumigem Duft."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Papaya"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("süß","moschusartig","butterig"); herkunft="Mittelamerika"; geschmack=@{acidity=1;sweetness=4;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Limette","Ingwer","Kokosmilch","Chili"); beschreibung="Tropenfrucht mit zartem, butterigem Fleisch und moschusartigem Aroma."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Kokosnuss"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("süß","nussig","cremig"); herkunft="Tropen weltweit"; geschmack=@{acidity=0;sweetness=3;bitterness=0;umami=1;spiciness=0;saltiness=1}; pairings=@("Ananas","Limette","Curry","Vanille"); beschreibung="Vielseitige Tropenfrucht – Wasser, Milch, Öl und Fleisch all haben kulinarischen Wert."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Pflaume"; kategorie="Obst"; saison=@("Sommer","Herbst"); aromaprofil=@("süß-sauer","fruchtig","würzig"); herkunft="Westasien/Europa"; geschmack=@{acidity=3;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Zimt","Vanille","Wildschwein","Rotwein"); beschreibung="Saftige Steinfrucht mit ausgewogener Süße und Säure, ideal für Saucen und Desserts."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Mirabelle"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("honigsüß","mild","fruchtig"); herkunft="Lothringen, Frankreich"; geschmack=@{acidity=2;sweetness=5;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Vanille","Mandel","Schlagsahne","Zimt"); beschreibung="Mini-Pflaume aus Lothringen mit außergewöhnlich honigartiger Süße, kurze Saison im August."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Pfirsich"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("süß","blumig","saftig"); herkunft="China"; geschmack=@{acidity=2;sweetness=4;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Prosciutto","Burrata","Basilikum","Vanille"); beschreibung="Samtig-saftige Steinfrucht mit blumiger Süße und unwiderstehlichem Aroma."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Aprikose"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("süß","leicht säuerlich","blumig"); herkunft="Zentralasien"; geschmack=@{acidity=3;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Mandel","Honig","Lavendel","Hühnchen"); beschreibung="Goldene Steinfrucht mit blumig-süßem Aroma, herrlich als Konfitüre oder getrocknet."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Johannisbeere"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("sauer","herb","fruchtig"); herkunft="Europa"; geschmack=@{acidity=5;sweetness=2;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Schokolade","Sahne","Vanille"); beschreibung="Säuerliche kleine Beere, rot oder schwarz, intensiver Geschmack besonders als Gelee."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Brombeere"; kategorie="Obst"; saison=@("Sommer","Herbst"); aromaprofil=@("süß-sauer","erdig","fruchtig"); herkunft="Europa"; geschmack=@{acidity=3;sweetness=3;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Zimt","Vanille","Schokolade"); beschreibung="Saftige Herbstbeere mit erdiger Tiefe und ausgewogener Süße-Säure."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Weintraube"; kategorie="Obst"; saison=@("Sommer","Herbst"); aromaprofil=@("süß","fruchtig","leicht gerbstoffig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Käse","Walnuss","Schinken","Aceto Balsamico"); beschreibung="Vielseitige Frucht für Käseplatten, Saucen und natürlich als Rosinenform."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Ananas"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("süß-sauer","tropisch","fruchtig"); herkunft="Südamerika"; geschmack=@{acidity=3;sweetness=4;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Schweinefleisch","Kokos","Rum","Ingwer"); beschreibung="Tropische Frucht mit charakteristischem Süße-Säure-Spiel und Enzymen, die Fleisch zart machen."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Limette"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("zitrisch","frisch","intensiv sauer"); herkunft="Südostasien"; geschmack=@{acidity=5;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Fisch","Kokos","Koriander","Ingwer"); beschreibung="Intensiv sauere Zitrusfrucht mit frischem Aroma, unverzichtbar in der asiatischen Küche."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Bergamotte"; kategorie="Obst"; saison=@("Winter"); aromaprofil=@("floral","zitrisch","parfümiert"); herkunft="Kalabrien, Italien"; geschmack=@{acidity=4;sweetness=1;bitterness=3;umami=0;spiciness=0;saltiness=0}; pairings=@("Schokolade","Vanille","Meeresfruechte","Earl Grey"); beschreibung="Hocharomatische Zitrusfrucht, bekannt als Earl Grey-Grundlage mit floraler Intensität."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Sanddorn"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("sehr sauer","tropisch","fruchtig"); herkunft="Norddeutschland/Sibirien"; geschmack=@{acidity=5;sweetness=2;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Sahne","Vanille","Honig","Mango"); beschreibung="Vitaminreiche nordische Beere mit extremer Säure und tropisch-fruchtiger Note."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Aronia"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("herb","adstringierend","fruchtig"); herkunft="Nordamerika/Europa"; geschmack=@{acidity=3;sweetness=2;bitterness=4;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Rotwein","Schokolade","Sahne"); beschreibung="Tieflila Beere mit hohem Antioxidantiengehalt und intensivem, adstringierendem Geschmack."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Tamarillo"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("süß-sauer","tomatenartig","würzig"); herkunft="Andenregion"; geschmack=@{acidity=4;sweetness=3;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Chili","Zwiebel","Koriander","Käse"); beschreibung="Baumtomate mit tomatenähnlichem aber süßerem Profil, vielseitig in Chutneys und Saucen."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Durian"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("intensiv","süß","cremig","kontrovers"); herkunft="Südostasien"; geschmack=@{acidity=1;sweetness=5;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Klebreis","Kokos","Ingwer","Schokolade"); beschreibung="'König der Früchte' – legendär cremig-süß, mit bekannt intensivem Geruch."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Jackfruit"; kategorie="Obst"; saison=@("Sommer","Herbst"); aromaprofil=@("süß","fruchtig","tropisch"); herkunft="Südostasien"; geschmack=@{acidity=1;sweetness=4;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("BBQ-Sauce","Ingwer","Limette","Kokos"); beschreibung="Weltgrößte Baumfrucht – unreif als fleischiges Pulled-Pork-Substitut, reif süß-tropisch."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Longan"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("süß","moschusartig","blumig"); herkunft="China"; geschmack=@{acidity=1;sweetness=5;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Lychee","Goji","Ingwer","Jasmin"); beschreibung="Kleiner, süßer Verwandter der Lychee mit weniger ausgeprägtem Aroma."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Goji"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("süßlich","herb","leicht sauer"); herkunft="China/Tibet"; geschmack=@{acidity=2;sweetness=3;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Mandel","Schokolade","Honig","Matcha"); beschreibung="Getrocknete rote Beere mit herbem Süßprofil und außergewöhnlichem Nährwert."; lagertemp="Raumtemperatur (trocken)"; einheit="Gramm" },
  @{ name="Acai"; kategorie="Obst"; saison=@("Ganzjährig"); aromaprofil=@("erdig","schokoladenartig","leicht herb"); herkunft="Brasilien"; geschmack=@{acidity=1;sweetness=2;bitterness=3;umami=0;spiciness=0;saltiness=0}; pairings=@("Banane","Mandel","Kokos","Cacao"); beschreibung="Amazonische Beere mit schokoladiger Note und adstringierender Tiefe, meist als Mus."; lagertemp="Tiefkühlung"; einheit="Gramm" },
  @{ name="Schlehe"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("sehr herb","adstringierend","fruchtig"); herkunft="Europa"; geschmack=@{acidity=4;sweetness=1;bitterness=4;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Rotwein","Gin","Honig"); beschreibung="Herbe Wildbeere, nach Frost genießbar, klassisch für Sloe Gin und Wildbegleiter."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Kornelkirsche"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("sauer","herb","fruchtig"); herkunft="Südeuropa"; geschmack=@{acidity=4;sweetness=2;bitterness=2;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Rotwein","Vanille","Marmelade"); beschreibung="Alte Kulturpflanze mit intensive Säure, traditionell zu Wild und als Konfitüre."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Mispel"; kategorie="Obst"; saison=@("Herbst","Winter"); aromaprofil=@("süß","zimtartig","nussig"); herkunft="Südeuropa/Asien"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Käse","Walnuss","Wild","Honig"); beschreibung="Historische Frucht, die nach Frost reift und ein einzigartiges karamellig-zimtiges Aroma entwickelt."; lagertemp="Raumtemperatur"; einheit="Gramm" },
  @{ name="Quitte"; kategorie="Obst"; saison=@("Herbst"); aromaprofil=@("würzig","floral","adstringierend"); herkunft="Kaukasus"; geschmack=@{acidity=3;sweetness=2;bitterness=3;umami=0;spiciness=0;saltiness=0}; pairings=@("Wild","Käse","Zimt","Nelke"); beschreibung="Goldgelbe Frucht mit einzigartigem Aroma, roh ungenießbar, gegart ein Hochgenuss."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Klementine"; kategorie="Obst"; saison=@("Winter"); aromaprofil=@("süß","zitrisch","mild"); herkunft="Algerien/Spanien"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Schokolade","Vanille","Ingwer","Mandel"); beschreibung="Kernlose Kreuzung aus Mandarine und Pomeranze mit milder, süßer Frische."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Mandarine"; kategorie="Obst"; saison=@("Winter"); aromaprofil=@("süß","zitrisch","aromatisch"); herkunft="China"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Schokolade","Zimt","Ingwer","Ente"); beschreibung="Klassische Winterzitrusfrucht mit intensivem aromatischen Duft und angenehmer Süße."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Lemon Verbena"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("intensiv zitronig","frisch","floral"); herkunft="Südamerika"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Fisch","Joghurt","Pfirsich","Weißwein"); beschreibung="Intensiv zitrische Kräuterpflanze – frischer als Zitronenmelisse, mit fast ätherischem Duft."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Blaubeere"; kategorie="Obst"; saison=@("Sommer"); aromaprofil=@("süß","leicht herb","fruchtig"); herkunft="Nordamerika"; geschmack=@{acidity=2;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Ziegenkäse","Vanille","Minze","Schokolade"); beschreibung="Wilde oder kultivierte Heidelbeere mit tiefem Beerenaroma und violetter Farbe."; lagertemp="0–4 °C"; einheit="Gramm" }
)
Insert-Batch $b2
