$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 1: Gemüse (40 items)
$b1 = @(
  @{ name="Pastinake"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("süßlich","nussig","erdig"); herkunft="Mitteleuropa"; geschmack=@{acidity=1;sweetness=3;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Karotte","Butter","Muskat","Petersilie"); beschreibung="Süßliche Wurzel mit nussigem Aroma, ideal für Suppen und Pürees."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Petersilienwurzel"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("würzig","erdnussig","aromatisch"); herkunft="Mitteleuropa"; geschmack=@{acidity=1;sweetness=2;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Sellerie","Lauch","Butter","Thymian"); beschreibung="Aromatische Wurzel mit intensivem Petersilienduft, unverzichtbar in Fonds."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Meerrettich"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("scharf","beißend","senfartig"); herkunft="Osteuropa"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=1;spiciness=5;saltiness=0}; pairings=@("Rindfleisch","Räucherlachs","Crème fraîche","Apfel"); beschreibung="Intensiv scharfe Wurzel, klassisch zur Tafelspitz und als Begleitung zu Fisch."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Kohlrabi"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("mild","leicht süß","kohlhaltig"); herkunft="Mitteleuropa"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Butter","Dill","Sahne","Speck"); beschreibung="Zarter Kohlspross mit mildem Geschmack, vielseitig roh oder gegart."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Wirsing"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("erdig","kohlhaltig","mild"); herkunft="Mitteleuropa"; geschmack=@{acidity=1;sweetness=2;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Speck","Muskat","Kartoffel","Kümmel"); beschreibung="Kräftiger Winterkohl mit weichen Blättern, klassisch geschmort oder als Roulade."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Rosenkohl"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("nussig","leicht bitter","kohlhaltig"); herkunft="Belgien"; geschmack=@{acidity=1;sweetness=2;bitterness=3;umami=2;spiciness=0;saltiness=0}; pairings=@("Speck","Kastanie","Butter","Muskat"); beschreibung="Miniaturkohl mit nussigem Biss, herrlich karamellisiert oder blanchiert."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Grünkohl"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("bitter","erdig","kräftig"); herkunft="Norddeutschland"; geschmack=@{acidity=1;sweetness=1;bitterness=4;umami=2;spiciness=0;saltiness=0}; pairings=@("Speck","Pinkel","Kartoffel","Senf"); beschreibung="Winterkohl mit intensivem Aroma, der nach Frost milder wird."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Radicchio"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("bitter","leicht nussig","knackig"); herkunft="Norditalien"; geschmack=@{acidity=1;sweetness=1;bitterness=4;umami=1;spiciness=0;saltiness=0}; pairings=@("Aceto Balsamico","Speck","Parmesan","Birne"); beschreibung="Bitterer roter Salat aus Venetien, wunderbar gegrillt oder als Risotto-Einlage."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Treviso"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("bitter","komplex","nussig"); herkunft="Treviso, Italien"; geschmack=@{acidity=1;sweetness=1;bitterness=4;umami=2;spiciness=0;saltiness=0}; pairings=@("Mozzarella","Risottoreis","Speck","Granatapfel"); beschreibung="Langköpfiger Radicchio aus Treviso mit feinerem Bitterprofil, DOP-geschützt."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Wasserkresse"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("pfeffrig","frisch","senfartig"); herkunft="Europa"; geschmack=@{acidity=1;sweetness=1;bitterness=3;umami=1;spiciness=3;saltiness=0}; pairings=@("Ei","Butter","Lachs","Zitrone"); beschreibung="Frisches Quellgemüse mit pfeffrigem Biss, klassisch im Watercress Soup."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Portulak"; kategorie="Gemüse"; saison=@("Sommer"); aromaprofil=@("säuerlich","saftig","mild"); herkunft="Mittelmeerraum"; geschmack=@{acidity=3;sweetness=1;bitterness=1;umami=1;spiciness=0;saltiness=1}; pairings=@("Joghurt","Zitrone","Minze","Tomate"); beschreibung="Saftiges Blattgemüse mit angenehmer Säure und leichter Salzigkeit."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Sauerampfer"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("intensiv sauer","frisch","zitrusartig"); herkunft="Europa"; geschmack=@{acidity=5;sweetness=0;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Fisch","Crème fraîche","Kartoffel","Ei"); beschreibung="Intensiv saures Wildkraut, das Saucen und Suppen eine frische Säure verleiht."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Löwenzahn"; kategorie="Gemüse"; saison=@("Frühling"); aromaprofil=@("bitter","frisch","nussig"); herkunft="Europa"; geschmack=@{acidity=1;sweetness=0;bitterness=4;umami=1;spiciness=0;saltiness=0}; pairings=@("Speck","Ei","Senf","Essig"); beschreibung="Wildkraut mit angenehm bitterem Aroma, jung als Salat, Blüten als Dekoration."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Okra"; kategorie="Gemüse"; saison=@("Sommer"); aromaprofil=@("mild","schleimig","grasig"); herkunft="Westafrika"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Tomate","Chili","Knoblauch","Limette"); beschreibung="Tropisches Schoten-Gemüse, das beim Kochen Bindung gibt – ideal in Eintöpfen."; lagertemp="8–12 °C"; einheit="Gramm" },
  @{ name="Bambus"; kategorie="Gemüse"; saison=@("Frühling"); aromaprofil=@("mild","knackig","leicht nussig"); herkunft="Ostasien"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Ingwer","Sojasauce","Sesam","Frühlingszwiebel"); beschreibung="Junge Bambussprossen mit knackiger Textur, Standard in der asiatischen Küche."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Wasserkastanie"; kategorie="Gemüse"; saison=@("Herbst"); aromaprofil=@("süßlich","knackig","mild"); herkunft="Ostasien"; geschmack=@{acidity=0;sweetness=3;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Ingwer","Frühlingszwiebel","Ente","Sojasauce"); beschreibung="Wässerige Knollen mit anhaltend knackiger Textur auch nach dem Garen."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Taro"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("stärkehaltig","nussig","erdig"); herkunft="Tropisch"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Kokosmilch","Ingwer","Garnelen","Koriander"); beschreibung="Tropische Knollenfrucht mit stärkereicher, cremiger Textur, vielseitig einsetzbar."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Yuca"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("stärkehaltig","mild","nussig"); herkunft="Südamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Limette","Koriander","Chili","Knoblauch"); beschreibung="Südamerikanische Maniokwurzel mit neutralem Geschmack und mehlig-cremiger Konsistenz."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Rettich"; kategorie="Gemüse"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("scharf","frisch","würzig"); herkunft="Ostasien/Europa"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=1;spiciness=4;saltiness=0}; pairings=@("Butter","Schnittlauch","Lachs","Miso"); beschreibung="Kräftiger Rettich mit scharfer Frische, roh im Salat oder gedämpft als Beilage."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Daikon"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("mild","leicht scharf","saftig"); herkunft="Japan/China"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=1;spiciness=2;saltiness=0}; pairings=@("Miso","Ingwer","Sojasauce","Dashi"); beschreibung="Milder japanischer Rettich, vielseitig roh, gedämpft oder als Beilage zu Sushi."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Mangold"; kategorie="Gemüse"; saison=@("Sommer","Herbst"); aromaprofil=@("erdig","mild","leicht salzig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=2;spiciness=0;saltiness=1}; pairings=@("Knoblauch","Zitrone","Parmesan","Butter"); beschreibung="Blattgemüse mit erdigem, spinatähnlichem Aroma und bunten Stielen."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Endivie"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("bitter","frisch","leicht nussig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=1;sweetness=1;bitterness=4;umami=1;spiciness=0;saltiness=0}; pairings=@("Grapefruit","Walnuss","Blauschimmelkäse","Birne"); beschreibung="Bitterer Wintersalat mit knackiger Textur und elegantem Aroma."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Feldsalat"; kategorie="Gemüse"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("mild","nussig","frisch"); herkunft="Europa"; geschmack=@{acidity=1;sweetness=1;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Speck","Ei","Walnuss","Kürbiskernöl"); beschreibung="Zarter Wintersalat mit leicht nussigem Geschmack, ideal mit Walnuss und Vinaigrette."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Rucola"; kategorie="Gemüse"; saison=@("Frühling","Sommer","Herbst"); aromaprofil=@("pfeffrig","nussig","bitter"); herkunft="Mittelmeerraum"; geschmack=@{acidity=1;sweetness=0;bitterness=3;umami=1;spiciness=3;saltiness=0}; pairings=@("Parmesan","Tomate","Pinienkern","Zitrone"); beschreibung="Pfeffriger Rucola mit nussig-bitterem Aroma, klassisch auf Pizza und in Salaten."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Grüne Bohne"; kategorie="Gemüse"; saison=@("Sommer"); aromaprofil=@("grasig","frisch","leicht süß"); herkunft="Mittelamerika"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Mandel","Butter","Knoblauch","Tomate"); beschreibung="Frische Brechbohnen mit grasigem Biss, vielseitig als Beilage oder Salat."; latertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Erbse"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("süßlich","frisch","grasig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=4;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Minze","Butter","Schinken","Ricotta"); beschreibung="Frische Erbsen mit natürlicher Süße, unverzichtbar im Frühjahr."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Spitzkohl"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("mild","leicht süß","frisch"); herkunft="Mitteleuropa"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Kümmel","Speck","Butter","Essig"); beschreibung="Zarter Frühsommerkohl mit milder Süße und feiner Textur."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Bimi"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht nussig","grasig"); herkunft="Japan/Spanien"; geschmack=@{acidity=1;sweetness=2;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Parmesan","Knoblauch","Chili","Olivenöl"); beschreibung="Zarte Brokkolikresse mit essbarem Stiel, milder und zarter als klassischer Brokkoli."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Palmherz"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht nussig","saftig"); herkunft="Südamerika"; geschmack=@{acidity=1;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=1}; pairings=@("Zitrone","Koriander","Chili","Olivenöl"); beschreibung="Delikater Palmkern mit butterzartem Biss, ideal in Salaten oder als Carpaccio."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Nopales"; kategorie="Gemüse"; saison=@("Sommer"); aromaprofil=@("leicht säuerlich","grasig","schleimig"); herkunft="Mexiko"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Jalapeño","Limette","Ei","Koriander"); beschreibung="Kaktusblätter der Feigenkaktus mit eigentümlicher Textur, klassisch in mexikanischen Gerichten."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Mais"; kategorie="Gemüse"; saison=@("Sommer"); aromaprofil=@("süßlich","buttrig","stärkehaltig"); herkunft="Mittelamerika"; geschmack=@{acidity=0;sweetness=4;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Butter","Limette","Chili","Koriander"); beschreibung="Süßer Sommermais, geröstet besonders aromatisch durch Karamellisierung."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Topinambur-Chips"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("nussig","erdig","artischockenartig"); herkunft="Nordamerika"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Schwarze Trüffel","Haselnuss","Thymian","Butter"); beschreibung="Zu Chips frittierter Topinambur – knusprige Beilage mit intensiv nussigem Aroma."; lagertemp="Raumtemperatur (trocken)"; einheit="Gramm" },
  @{ name="Jicama"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("frisch","knackig","leicht süß"); herkunft="Mexiko"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Limette","Chili","Mango","Koriander"); beschreibung="Mexikanische Knollenfrucht mit apfelähnlicher Frische und knackiger Textur."; lagertemp="13–15 °C"; einheit="Gramm" },
  @{ name="Steckrübe"; kategorie="Gemüse"; saison=@("Herbst","Winter"); aromaprofil=@("erdig","leicht süß","kohl-artig"); herkunft="Nordeuropa"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Butter","Muskat","Thymian","Speck"); beschreibung="Derbe Winterrübe mit erdiger Süße, langsam geschmort ein wahrer Gaumenschmeichler."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Romanasalat"; kategorie="Gemüse"; saison=@("Frühling","Sommer"); aromaprofil=@("frisch","mild","knackig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=1;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Parmesan","Sardellen","Zitrone","Knoblauch"); beschreibung="Knackiger Römischer Salat, Basis des klassischen Caesar Salad."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Eisbergsalat"; kategorie="Gemüse"; saison=@("Ganzjährig"); aromaprofil=@("frisch","wässrig","neutral"); herkunft="USA"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Thousand Island","Tomaten","Speck","Croutons"); beschreibung="Knackiger, wässriger Salat – seine Kälte und Crunch sind sein Markenzeichen."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Eichblattsalat"; kategorie="Gemüse"; saison=@("Frühling","Herbst"); aromaprofil=@("nussig","mild","leicht bitter"); herkunft="Frankreich"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Vinaigrette","Walnuss","Apfel","Blauschimmelkäse"); beschreibung="Charakteristisch geformter Blattsalat mit nussigem, leicht bitterem Aroma."; lagertemp="0–4 °C"; einheit="Gramm" }
)
Insert-Batch $b1
