$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 6: Fermentiertes & Kondimente (30) + Öle & Essige (20) = 50 items
$b6 = @(
  @{ name="Doenjang"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","erdnussig","würzig"); herkunft="Korea"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=5;spiciness=0;saltiness=4}; pairings=@("Tofu","Zucchini","Sesam","Sesamöl"); beschreibung="Koreanische Sojabohnenpaste – intensiver und komplexer als japanisches Miso, Basis von Doenjang-jjigae."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Douchi"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("salzig","funk","komplex"); herkunft="China"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=5;spiciness=0;saltiness=5}; pairings=@("Fleisch","Fisch","Tofu","Knoblauch"); beschreibung="Gesalzene fermentierte schwarze Bohnen – Umami-Bombe der chinesischen Küche."; lagertemp="Trocken/Kühlschrank"; einheit="Gramm" },
  @{ name="Tempeh"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("nussig","pilzartig","mild"); herkunft="Indonesien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=1}; pairings=@("Sojasauce","Chili","Ingwer","Koriander"); beschreibung="Fermentierter Sojabohnenkuchen mit nussig-pilzartigem Aroma und proteinreicher Struktur."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Natto"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","ammoniakalisch","erdig"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=5;spiciness=0;saltiness=2}; pairings=@("Reis","Sojasauce","Senf","Schnittlauch"); beschreibung="Japanische fermentierte Sojabohnen mit fadenziehender Textur und intensivem Aroma."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Kimchi"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","sauer","fermentiert"); herkunft="Korea"; geschmack=@{acidity=4;sweetness=1;bitterness=0;umami=4;spiciness=4;saltiness=3}; pairings=@("Reis","Schweinefleisch","Tofu","Ei"); beschreibung="Koreanisches Nationalgericht – fermentierter Kohl mit Gochugaru und Fischsauce."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Sauerkraut"; kategorie="Fermentiertes"; saison=@("Herbst","Winter"); aromaprofil=@("sauer","würzig","mild"); herkunft="Deutschland/Europa"; geschmack=@{acidity=4;sweetness=0;bitterness=0;umami=2;spiciness=0;saltiness=2}; pairings=@("Schweinefleisch","Wurst","Kartoffel","Senf"); beschreibung="Milchsauer vergorener Weißkohl – probiotisch, sauer, unverzichtbar zur Wurst."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Worcestershire"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("würzig","sauer","komplex"); herkunft="Worcester, England"; geschmack=@{acidity=3;sweetness=2;bitterness=1;umami=4;spiciness=1;saltiness=3}; pairings=@("Steak","Caesar Salad","Bloody Mary","Ragù"); beschreibung="Geheimrezept-Sauce aus Sardellen, Tamarinde und Essig – komplexe Umami-Tiefe."; lagertemp="Raumtemperatur (nach Öffnung Kühlschrank)"; einheit="Milliliter" },
  @{ name="Tabasco"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","sauer","fruchtig"); herkunft="Avery Island, Louisiana, USA"; geschmack=@{acidity=4;sweetness=0;bitterness=0;umami=0;spiciness=5;saltiness=2}; pairings=@("Bloody Mary","Austern","Eier","Burgersauce"); beschreibung="Dreizutaten-Klassiker aus Chili, Salz und Essig – seit 1869 unverändert."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Sriracha"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","süßlich","knoblauchig"); herkunft="Si Racha, Thailand / USA"; geschmack=@{acidity=2;sweetness=2;bitterness=0;umami=1;spiciness=4;saltiness=2}; pairings=@("Pho","Burger","Eier","Ramen"); beschreibung="Süßlich-scharfe Chilisauce mit Knoblauch – Kultkondiment aus Südostasien."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Sambal Oelek"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("sehr scharf","frisch","fruchtig"); herkunft="Indonesien"; geschmack=@{acidity=2;sweetness=0;bitterness=0;umami=1;spiciness=5;saltiness=2}; pairings=@("Noodles","Seafood","Spiegelei","Ramen"); beschreibung="Reine Chilipaste ohne Füllstoffe – reines Chili-Feuer für jede Küche."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Chermoula"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("würzig","kräuterig","zitrusartig"); herkunft="Nordafrika"; geschmack=@{acidity=2;sweetness=0;bitterness=1;umami=1;spiciness=2;saltiness=2}; pairings=@("Fisch","Hühnchen","Gemüse","Lamm"); beschreibung="Nordafrikanische Würzpaste aus Koriander, Petersilie, Cumin und Zitrone – vielseitige Marinade."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Zhug"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","kräuterig","frisch"); herkunft="Jemen"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=0;spiciness=5;saltiness=2}; pairings=@("Hummus","Falafel","Lamm","Ei"); beschreibung="Jemenitische Chilisauce mit frischen Kräutern – Israels Antwort auf Harissa."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Ponzu"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("sauer","zitrisch","umami"); herkunft="Japan"; geschmack=@{acidity=4;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=3}; pairings=@("Sashimi","Gyoza","Shabu-Shabu","Tofu"); beschreibung="Japanische Zitrus-Sojasauce aus Yuzu und Dashi – frisch-säuerliche Umami-Tiefe."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Sake"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht süßlich","umami"); herkunft="Japan"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Sojasauce","Miso","Fisch","Schweinefleisch"); beschreibung="Japanischer Reiswein – als Kochwein unverzichtbar in Teriyaki, Miso-Marinaden und Dashi."; lagertemp="0–4 °C (nach Öffnung)"; einheit="Milliliter" },
  @{ name="Reisessig"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("mild sauer","leicht süßlich","frisch"); herkunft="China/Japan"; geschmack=@{acidity=3;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Sushi","Gurke","Salat","Dressing"); beschreibung="Milder, leicht süßlicher Reisessig – milder als Weißweinessig, ideal für Sushi und Dressings."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Tamari"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","würzig","dunkel"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=5;spiciness=0;saltiness=4}; pairings=@("Sashimi","Ramen","Gyoza","Marinaden"); beschreibung="Gluten­freie japanische Sojasauce mit tiefem, rundem Umami und weniger Salzigkeit."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Miso Aka"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","salzig","tief fermentiert"); herkunft="Japan"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=5;spiciness=0;saltiness=5}; pairings=@("Suppe","Rindfleisch","Aubergine","Butter"); beschreibung="Rotes Hatcho-Miso – länger fermentiert als Shiro, intensiv und salzig mit enormer Umami-Tiefe."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Dobanjiang"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","salzig","intensiv fermentiert"); herkunft="Sichuan, China"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=4;spiciness=4;saltiness=5}; pairings=@("Tofu","Schweinefleisch","Mapo","Öl"); beschreibung="Sichuan-Bohnenpaste aus fermentierten Fava-Bohnen und Chili – Herz des Mapo Tofu."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Tapenade"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("salzig","olivenölig","würzig"); herkunft="Provence, Frankreich"; geschmack=@{acidity=1;sweetness=0;bitterness=2;umami=3;spiciness=0;saltiness=4}; pairings=@("Brot","Lamm","Tomate","Ziegenkäse"); beschreibung="Provençalische Paste aus schwarzen Oliven, Kapern und Sardellen – konzentrierter Mittelmeer-Geschmack."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Adjika"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("scharf","kräuterig","knoblauchig"); herkunft="Abchasien/Georgien"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=1;spiciness=4;saltiness=2}; pairings=@("Gegrilltes Fleisch","Käse","Hühnchen","Aubergine"); beschreibung="Kaukasische Würzpaste aus getrockneter Chili, Knoblauch und Kräutern – kein Zusatz von Tomaten."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Gremolata"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("frisch","zitrisch","kräuterig"); herkunft="Mailand, Italien"; geschmack=@{acidity=2;sweetness=0;bitterness=1;umami=0;spiciness=0;saltiness=1}; pairings=@("Osso Buco","Risotto","Fisch","Lamm"); beschreibung="Mailänder Topping aus Zitronen­zeste, Knoblauch und Petersilie – belebt das Osso Buco."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Persillade"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("frisch","kräuterig","knoblauchig"); herkunft="Frankreich"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=0;spiciness=0;saltiness=1}; pairings=@("Lamm","Schnecken","Muscheln","Gemüse"); beschreibung="Französische Mischung aus Petersilie und Knoblauch – einfach, wirkungsvoll, frisch."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Chimichurri"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("frisch","kräuterig","säuerlich"); herkunft="Argentinien"; geschmack=@{acidity=3;sweetness=0;bitterness=1;umami=0;spiciness=1;saltiness=2}; pairings=@("Rindfleisch","Churrasco","Hühnchen","Crevetten"); beschreibung="Argentinisches Nationalkondiment aus Petersilie, Knoblauch und Rotweinessig zu Grillgut."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Amazake"; kategorie="Fermentiertes"; saison=@("Winter"); aromaprofil=@("süßlich","mild","reiswürzig"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=4;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Ingwer","Mochi","Eis","Dashi"); beschreibung="Fermentiertes Reisgetränk mit natürlicher Süße durch Koji-Enzyme – alkoholarm, nährend."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Hoisin Sauce"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","würzig","dunkel"); herkunft="China"; geschmack=@{acidity=1;sweetness=4;bitterness=0;umami=3;spiciness=1;saltiness=3}; pairings=@("Ente","Frühlings­rollen","Peking Ente","Ramen"); beschreibung="Süß-würzige chinesische Glasur­sauce – unverzichtbar bei Peking Ente und als Dip."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Austernsauce"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("salzig","süßlich","umami"); herkunft="Guangdong, China"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=5;spiciness=0;saltiness=4}; pairings=@("Brokkoli","Rindfleisch","Tofu","Nudeln"); beschreibung="Dicke Sauce aus Austernextrakt – süßlich-salmig und reich an Umami, essentiell in der kantonesischen Küche."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Fischsauce"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","salzig","fischig"); herkunft="Thailand/Vietnam"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=5;spiciness=0;saltiness=5}; pairings=@("Pad Thai","Salat","Stir Fry","Kokos"); beschreibung="Fermentierte Anchovy-Sauce – Rückgrat der südostasiatischen Küche, sparsam dosieren."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Mirin"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","mild","reisaromatisch"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=4;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Teriyaki","Sojasauce","Sake","Dashi"); beschreibung="Japanischer Süßreiswein mit natürlicher Süße – verleiht Glasuren Glanz und Tiefe."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Colatura di Alici"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","salzig","fischig","umami"); herkunft="Cetara, Italien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=5;spiciness=0;saltiness=5}; pairings=@("Pasta","Tomaten","Olivenöl","Petersilie"); beschreibung="Italienisches Anchovy-Destillat aus Cetara – wenige Tropfen veredeln jede Pasta."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Nduja"; kategorie="Fermentiertes"; saison=@("Ganzjährig"); aromaprofil=@("sehr scharf","fettig","würzig"); herkunft="Kalabrien, Italien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=4;spiciness=5;saltiness=3}; pairings=@("Pizza","Pasta","Burrata","Crostini"); beschreibung="Streichwurst aus Kalabrien mit intensiver Chilischärfe und reichem Schweinefleischaroma."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Olivenöl extra vergine"; kategorie="Öle & Fette"; saison=@("Herbst"); aromaprofil=@("fruchtig","pfeffrig","grasig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=1;spiciness=2;saltiness=0}; pairings=@("Tomate","Fisch","Salat","Brot"); beschreibung="Kaltgepresstes Olivenöl der höchsten Qualitätsstufe – fruchtig, pfeffrig, peppig."; lagertemp="Dunkel, Raumtemperatur"; einheit="Milliliter" },
  @{ name="Walnussöl"; kategorie="Öle & Fette"; saison=@("Herbst"); aromaprofil=@("nussig","intensiv","mild bitter"); herkunft="Frankreich/USA"; geschmack=@{acidity=1;sweetness=1;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Rucola","Ziegenkäse","Walnuss","Birne"); beschreibung="Kaltgepresstes Walnussöl mit intensiv nussigem Aroma – nur für Dressings, nicht zum Erhitzen."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Pistazienöl"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("intensiv nussig","süßlich","reich"); herkunft="Iran/Türkei"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Dessert","Meeresfrüchte","Salat","Joghurt"); beschreibung="Luxuriöses Pistazienkernöl mit intensivem Aroma – kostbar und intensiv dosieren."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Steirisches Kürbiskernöl"; kategorie="Öle & Fette"; saison=@("Herbst"); aromaprofil=@("nussig","intensiv","dunkel"); herkunft="Steiermark, Österreich"; geschmack=@{acidity=0;sweetness=1;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Feldsalat","Kürbissuppe","Käse","Joghurt"); beschreibung="g.g.A.-geschütztes Kürbiskernöl aus der Steiermark – dunkelgrün, intensiv, nussig."; lagertemp="Trocken (dunkel)"; einheit="Milliliter" },
  @{ name="Sherryessig"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("komplex","nussig","leicht süßlich"); herkunft="Jerez, Spanien"; geschmack=@{acidity=3;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Gazpacho","Salmorejo","Linsen","Speck"); beschreibung="In Solera-Fässern gereifter Sherryessig mit tiefer, nussig-karamelliger Komplexität."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Balsamico Tradizionale"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("komplex","süß-sauer","intensiv"); herkunft="Modena/Reggio Emilia, Italien"; geschmack=@{acidity=3;sweetness=4;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Parmesan","Erdbeere","Risotto","Foie Gras"); beschreibung="DOP-geschützter Traditionsbalsamico, 12-25 Jahre in Holzfässern gereift – ein Tropfen reicht."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Weißer Balsamico"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("mild süß","frisch","leicht fruchtig"); herkunft="Modena, Italien"; geschmack=@{acidity=3;sweetness=3;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Salat","Fisch","Jakobsmuschel","Gemüse"); beschreibung="Heller, milder Balsamico ohne Karamell-Bitterkeit – schont die Farbe heller Gerichte."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Granatapfelmelasse"; kategorie="Öle & Fette"; saison=@("Herbst","Winter"); aromaprofil=@("süß-sauer","intensiv","fruchtig"); herkunft="Persien/Naher Osten"; geschmack=@{acidity=4;sweetness=4;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Lamm","Walnuss","Hähnchen","Aubergine"); beschreibung="Eingekochter Granatapfelsaft – sauer-süß und intensiv, essentiell im persischen Fesenjān."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Champagneressig"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("elegant","mild","leicht fruchtig"); herkunft="Champagne, Frankreich"; geschmack=@{acidity=3;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Jakobsmuschel","Salat","Vinaigrette","Sauce Béarnaise"); beschreibung="Elegantester aller Essige aus Champagnerwein – mild, frisch und ohne Ecken."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Umeboshi Essig"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("sehr sauer","salzig","fruchtig"); herkunft="Japan"; geschmack=@{acidity=5;sweetness=0;bitterness=0;umami=2;spiciness=0;saltiness=4}; pairings=@("Salat","Gurke","Avocado","Onigiri"); beschreibung="Salz-Säure-Sud aus der Umeboshi-Fermentation – kräftig sauer, tief salzig."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Macadamiaöl"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("mild","buttrig","nussig"); herkunft="Australien/Hawaii"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Salat","Fisch","Dessert","Garnelen"); beschreibung="Feines Nussöl mit buttrigem Aroma und hohem Rauchpunkt, ideal auch zum Anbraten."; lagertemp="Trocken (dunkel)"; einheit="Milliliter" },
  @{ name="Kokosnussöl"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("mild-süßlich","kokosartig","neutral (raffiniert)"); herkunft="Tropen weltweit"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Curry","Backwaren","Popcorn","Wok-Gerichte"); beschreibung="Nativ mit Kokosduft oder raffiniert neutral – vielseitig für Braten und Backen."; lagertemp="Raumtemperatur"; einheit="Milliliter" },
  @{ name="Trüffelöl schwarz"; kategorie="Öle & Fette"; saison=@("Ganzjährig"); aromaprofil=@("intensiv trüffelartig","erdig","nussig"); herkunft="Frankreich/Italien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=4;spiciness=0;saltiness=0}; pairings=@("Pasta","Risotto","Kartoffelpüree","Ei"); beschreibung="Olivenöl aromatisiert mit Schwarztrüffelextrakt – spargsam dosiert ein Gericht adelnd."; lagertemp="Trocken (dunkel)"; einheit="Milliliter" }
)
Insert-Batch $b6
