$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 5: Kräuter & Gewürze (42 items)
$b5 = @(
  @{ name="Asafoetida"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("schwefelartig","lauch","intensiv"); herkunft="Iran/Afghanistan"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=3;spiciness=1;saltiness=0}; pairings=@("Linsen","Kartoffel","Blumenkohl","Knoblauch"); beschreibung="Getrocknetes Harz mit krassem Rohduft, der sich im Öl in edles Lauch-Umami verwandelt."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Bockshornklee"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("bitter","ahornsirupartig","würzig"); herkunft="Mittelmeer/Südostasien"; geschmack=@{acidity=0;sweetness=2;bitterness=3;umami=1;spiciness=0;saltiness=0}; pairings=@("Curry","Linse","Tomate","Kartoffel"); beschreibung="Same mit charakteristischem Ahornsirupduft, essenziell in Curry-Mischungen."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Pandan"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("floral","vanillisch","grasig"); herkunft="Südostasien"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Klebreis","Kokosmilch","Mango","Kuchen"); beschreibung="Grünes Blatt der 'Vanille des Ostens' – verleiht Speisen unverwechselbaren Blumenduft."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Lavendel"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("floral","seifig","süßlich"); herkunft="Provence, Frankreich"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Lamm","Schokolade","Honig","Zitrone"); beschreibung="Sorgfältig dosiert verleiht Lavendel Gerichten Provençalische Poesie – zu viel wird seifig."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Hibiskus"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("sauer","fruchtig","blumig"); herkunft="Tropisch weltweit"; geschmack=@{acidity=5;sweetness=2;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Erdbeere","Himbeeere","Kokos","Mango"); beschreibung="Getrocknete Kelche mit leuchtend roter Farbe und intensiver Fruchtsäure."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Schwarzer Knoblauch"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("komplex","süßlich","balsamisch"); herkunft="Korea/Japan"; geschmack=@{acidity=1;sweetness=3;bitterness=1;umami=5;spiciness=0;saltiness=0}; pairings=@("Rindfleisch","Pilze","Parmesan","Olivenöl"); beschreibung="Fermentierter Knoblauch mit tiefer, karamelliger Süße ohne Schärfe – Umami pur."; lagertemp="Raumtemperatur (trocken)"; einheit="Gramm" },
  @{ name="Urfa Biber"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("schokoladenartig","rauchig","mild scharf"); herkunft="Şanlıurfa, Türkei"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=2;spiciness=3;saltiness=1}; pairings=@("Lamm","Joghurt","Aubergine","Olivenöl"); beschreibung="Dunkelroter türkischer Pfeffer mit schokoladenartig-rauchigem Aroma und milder Schärfe."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Aleppo Pfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("fruchtig","mild scharf","leicht ölig"); herkunft="Aleppo, Syrien"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=1;spiciness=3;saltiness=1}; pairings=@("Hühnchen","Lamm","Hummus","Joghurt"); beschreibung="Halbgetrocknete syrische Chili mit mittlerer Schärfe und reichem, fruchtigen Aroma."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Grüner Pfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("frisch","scharf","grasig"); herkunft="Kerala, Indien"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=0;spiciness=4;saltiness=0}; pairings=@("Steak","Sahnesauce","Ente","Cognac"); beschreibung="Unreife Pfefferkörner mit frisch-grasiger Schärfe – Basis der Klassischen Pfeffersauce."; lagertemp="0–4 °C (in Lake)"; einheit="Gramm" },
  @{ name="Langer Pfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("komplex","warm","pfeffrig"); herkunft="Indien/Südostasien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=4;saltiness=0}; pairings=@("Wild","Schokolade","Käse","Honig"); beschreibung="Historischer Pfeffer mit wärmender Schärfe und Zimtnote – vor dem Chili verehrt."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Kubebenpfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("scharf","campheartig","frisch"); herkunft="Indonesien/Westafrika"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=0;spiciness=4;saltiness=0}; pairings=@("Lammfleisch","Eintopf","Tajine","Ras el Hanout"); beschreibung="Gestielte Pfefferkörner mit campheartigem Aroma und langanhaltender Schärfe."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Voatsiperifery"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("floral","scharf","komplex"); herkunft="Madagaskar"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=3;saltiness=0}; pairings=@("Mango","Schokolade","Meeresfruechte","Vanille"); beschreibung="Wilder madagassischer Pfeffer mit einzigartigem blumig-fruchtigen Aroma – der edelste Pfeffer."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Kampot Pfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("fruchtig","floral","scharf"); herkunft="Kampot, Kambodscha"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=0;spiciness=4;saltiness=0}; pairings=@("Krabbenfleisch","Tintenfisch","Steak","Zitrone"); beschreibung="GI-geschützter Edelpepper mit floraler Frische, am besten frisch gemahlen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Nigella"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("würzig","leicht bitter","zwiebelartig"); herkunft="Mittelmeer/Naher Osten"; geschmack=@{acidity=0;sweetness=0;bitterness=2;umami=1;spiciness=1;saltiness=0}; pairings=@("Brot","Käse","Aubergine","Linsen"); beschreibung="Schwarzkümmel – nicht identisch mit Kümmel – auf Fladenbrot und in der Naan-Küche."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Annatto"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("mild","erdnussig","leicht süßlich"); herkunft="Tropisch Amerika"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Hühnchen","Fisch","Reis","Schweinefleisch"); beschreibung="Rotorange Samen der Bixa-Pflanze – färbt Speisen safranähnlich, Aroma mild-nussig."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Epazote"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("harzig","intensiv","medizinisch"); herkunft="Mexiko"; geschmack=@{acidity=0;sweetness=0;bitterness=2;umami=0;spiciness=1;saltiness=0}; pairings=@("Schwarze Bohnen","Mais","Ziegenkäse","Chili"); beschreibung="Mexikanisches Kräuterwunder, unverzichtbar in schwarzen Bohnen, wirkt auch entblähend."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Melisse"; kategorie="Kräuter & Gewürze"; saison=@("Frühling","Sommer"); aromaprofil=@("zitronig","frisch","mild"); herkunft="Südeuropa"; geschmack=@{acidity=1;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Fisch","Joghurt","Dessert","Sommersalat"); beschreibung="Zitronenmelisse mit frischem Zitrus-Kräuterduft, ideal für leichte Sommer gerichte."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Curryblatt"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("komplex","currywürzig","warm"); herkunft="Südindien/Sri Lanka"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=2;spiciness=1;saltiness=0}; pairings=@("Kokosöl","Senfsamen","Linsen","Hühnchen"); beschreibung="Frisches Blatt mit unverwechselbarem Curryaroma, im Öl kurz geröstet der Schlüssel zum echten Curry."; lagertemp="0–4 °C (frisch)"; einheit="Gramm" },
  @{ name="Zitronenverbene"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("intensiv zitronig","frisch","blumig"); herkunft="Südamerika"; geschmack=@{acidity=2;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Fisch","Pfirsich","Joghurt","Vanilleeis"); beschreibung="Stärkste Zitrusnote aller Kräuter – frischer und intensiver als Zitronenmelisse."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Fenchelsamen"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","anisartig","frisch"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Fisch","Schwein","Brot","Tomate"); beschreibung="Aromatischer Same mit Anisduft, klassisch in der Italienischen Salumeria und in Fischgerichten."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Lorbeer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("würzig","eukalyptusartig","mild"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=0;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Fond","Eintopf","Lamm","Kartoffel"); beschreibung="Unverzichtbares Kochkraut in jedem Fond, Bouquet garni und Schmorgericht."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Salbei"; kategorie="Kräuter & Gewürze"; saison=@("Sommer","Herbst"); aromaprofil=@("würzig","campheartig","erdnussig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=0;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Butter","Pasta","Kalbfleisch","Kürbis"); beschreibung="Klassisch in brauner Butter zu Ravioli – aromatisch-würzig mit harzig-campheartigem Profil."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Oregano"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("würzig","herb","mediterran"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=0;bitterness=2;umami=1;spiciness=1;saltiness=0}; pairings=@("Tomate","Olivenöl","Lamm","Mozzarella"); beschreibung="Das mediterrane Kräuterwunderwerk – getrocknet intensiver als frisch, essentiell auf Pizza."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Dill"; kategorie="Kräuter & Gewürze"; saison=@("Frühling","Sommer"); aromaprofil=@("frisch","anisartig","grasig"); herkunft="Europa/Zentralasien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Lachs","Gurke","Joghurt","Kartoffel"); beschreibung="Frisches Kräuterwunder der nordischen Küche – unverzichtbar zu Lachs und Gurke."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Kerbel"; kategorie="Kräuter & Gewürze"; saison=@("Frühling"); aromaprofil=@("mild","anisartig","frisch"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Ei","Fisch","Suppe","Joghurt"); beschreibung="Zartes Frühlingskraut mit leichter Anisnote, zählt zu den klassischen Fines herbes."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Borretsch"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("gurkenartig","frisch","mild"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Salat","Joghurt","Erdbeere","Ziegenkäse"); beschreibung="Gurkenkraut mit essbaren blauen Blüten, frisch wie Gurke – ideal in Sommercocktails."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Nelke"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","eugenolhaltig","warm"); herkunft="Molukken, Indonesien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=2;saltiness=0}; pairings=@("Zimt","Orangen","Wild","Lebkuchen"); beschreibung="Intensives Gewürz mit charakteristischem Eugenol-Aroma, dosiert einsetzen in Wintergewürzen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Koriandersamen"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("zitrusartig","warm","leicht süßlich"); herkunft="Mittelmeerraum/Indien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=0;spiciness=1;saltiness=0}; pairings=@("Currygewürze","Möhre","Linsen","Lamm"); beschreibung="Frisch gemörserter Same mit floraler Zitrusnote – sehr anders als das frische Korianderkraut."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Muskat"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("warm","würzig","süßlich"); herkunft="Banda-Inseln, Indonesien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=2;saltiness=0}; pairings=@("Kartoffel","Spinat","Sahne","Béchamel"); beschreibung="Frisch geriebene Muskatnuss mit warmem Würzprofil – unverzichtbar in Béchamel."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Piment"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("warm","gewürznelkenartig","pfeffrig"); herkunft="Karibik/Mittelamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=0;spiciness=2;saltiness=0}; pairings=@("Wild","Lamm","Lebkuchen","Glühwein"); beschreibung="'Allspice' – vereint Aromen von Nelke, Muskat und Zimt in einer einzigen Beere."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Cayenne"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("intensiv scharf","trocken","wenig Aroma"); herkunft="Cayenne, Französisch-Guayana"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=0;spiciness=5;saltiness=0}; pairings=@("Schokolade","Mango","Garnelen","Saucen"); beschreibung="Reine Schärfe ohne Ablenkung – die Schärfebombe unter den Chilipulvern."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Tasmanischer Bergpfeffer"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("anfangs fruchtig","dann extrem scharf","komplex"); herkunft="Tasmanien, Australien"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=0;spiciness=5;saltiness=0}; pairings=@("Wild","Schokolade","Lamm","Reifekäse"); beschreibung="Einzigartiger Pfeffer – zuerst fruchtig, dann tritt eine verzögerte, intensive Schärfe ein."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Rose (Blütenblätter)"; kategorie="Kräuter & Gewürze"; saison=@("Sommer"); aromaprofil=@("floral","süßlich","leicht tanninhaltig"); herkunft="Marokko/Iran/Türkei"; geschmack=@{acidity=1;sweetness=2;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Lamm","Pistazie","Joghurt","Honig"); beschreibung="Getrocknete Rosenblätter verleihen Gerichten persische Eleganz – sparsam dosiert."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Kardamom schwarz"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("rauchig","mentholartig","kräuterig"); herkunft="Himalaya-Region"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=0;spiciness=1;saltiness=0}; pairings=@("Fleischgerichte","Biriyani","Eintopf","Chai"); beschreibung="Schwarzer Kardamom – rauchiger Bruder des grünen, für herzhafte Gerichte nicht Desserts."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Galgant"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("scharf","pfeffrig","zitrusartig"); herkunft="Thailand/Südostasien"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=0;spiciness=3;saltiness=0}; pairings=@("Kokosmilch","Lemongrass","Kaffirlimette","Hühnchen"); beschreibung="Ingwerverwandter mit schärferem, zitruslastigerem Profil – Basis für Thai-Curry-Pasten."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Kaffir-Limetten-Blatt"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("intensiv zitrusartig","floral","komplex"); herkunft="Südostasien"; geschmack=@{acidity=1;sweetness=0;bitterness=1;umami=0;spiciness=0;saltiness=0}; pairings=@("Kokosmilch","Garnelen","Hühnchen","Thai-Curry"); beschreibung="Doppelblatt der Kaffir-Limette – unvergleichlich aromatisch in Thai-Curries und Tom Kha."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Berbere"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("komplex","scharf","warm"); herkunft="Äthiopien/Eritrea"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=1;spiciness=4;saltiness=0}; pairings=@("Lamm","Linsen","Injera","Hühnchen"); beschreibung="Äthiopische Gewürzblende aus 15+ Zutaten – fruchtig, warm und intensiv scharf."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Baharat"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("warm","würzig","duftend"); herkunft="Levante/Arabische Halbinsel"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=1;spiciness=2;saltiness=0}; pairings=@("Lamm","Kichererbse","Aubergine","Reis"); beschreibung="Arabische Gewürzmischung mit warmem, aromatischem Profil aus Pfeffer, Nelke und Kardamom."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Za'atar"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("herb","nussig","zitrusartig"); herkunft="Naher Osten/Levante"; geschmack=@{acidity=2;sweetness=0;bitterness=1;umami=2;spiciness=0;saltiness=2}; pairings=@("Olivenöl","Fladenbrot","Joghurt","Hühnchen"); beschreibung="Levantinische Gewürzmischung aus Thymian, Sesam, Sumac – auf Brot mit Olivenöl unvergleichlich."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Dukkah"; kategorie="Kräuter & Gewürze"; saison=@("Ganzjährig"); aromaprofil=@("nussig","warm","würzig"); herkunft="Ägypten"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=2;spiciness=1;saltiness=1}; pairings=@("Olivenöl","Brot","Gemüse","Lamm"); beschreibung="Ägyptische Nuss-Gewürzmischung zum Dippen – knackig, nussig und aromatisch warm."; lagertemp="Trocken"; einheit="Gramm" }
)
Insert-Batch $b5
