$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 4: Pilze (18) + Käse/Milchprodukte (22) = 40 items
$b4 = @(
  @{ name="Austernpilz"; kategorie="Pilze"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("mild","nussig","seidig"); herkunft="Weltweit"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Butter","Thymian","Knoblauch","Parmesan"); beschreibung="Zarter Speisepilz mit seidiger Textur und mildem nussigen Aroma – vielseitig einsetzbar."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Königsausternpilz"; kategorie="Pilze"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("fest","nussig","umami"); herkunft="Mittelmeer/Asien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Miso","Butter","Zitrone","Thymian"); beschreibung="Größter Austernpilz mit festem Stiel, der bei Hitze knusprig wird – ideal zum Braten."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Maitake"; kategorie="Pilze"; saison=@("Herbst"); aromaprofil=@("würzig","aromatisch","waldig"); herkunft="Japan/Nordamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=4;spiciness=0;saltiness=1}; pairings=@("Sojasauce","Sesam","Sake","Thymian"); beschreibung="'Tanzpilz' mit intensivem Waldpilzaroma und federleichter, fächerartiger Struktur."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Lion's Mane"; kategorie="Pilze"; saison=@("Herbst","Winter"); aromaprofil=@("mild","krabbenfleischähnlich","süßlich"); herkunft="Japan/Nordamerika"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Butter","Knoblauch","Zitrone","Sojasauce"); beschreibung="Exotisch aussehender Pilz mit erstaunlich an Scallops oder Hummer erinnerndem Fleisch."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Nameko"; kategorie="Pilze"; saison=@("Herbst","Winter"); aromaprofil=@("mild","etwas schleimig","nussig"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Miso","Dashi","Sake","Sobanudeln"); beschreibung="Japanischer Pilz mit charakteristischer Gallertschicht, klassisch in Miso-Suppe."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Mu-Err"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("mild","knackig","neutral"); herkunft="China/Ostasien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=2;spiciness=0;saltiness=1}; pairings=@("Ingwer","Sojasauce","Sesam","Lauch"); beschreibung="Chinesisches Holzohr mit einzigartig knackiger Textur, nimmt Aromen gut auf."; lagertemp="Trocken (getrocknet)"; einheit="Gramm" },
  @{ name="Champignon"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("mild","erdig","nussig"); herkunft="Europa/Weltweit"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=0}; pairings=@("Butter","Knoblauch","Petersilie","Sahne"); beschreibung="Meistgegessener Pilz der Welt – mild und vielseitig, intensiviert sich mit dem Garen."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Portobello"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("fleischig","intensiv","erdig"); herkunft="Europa/USA"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Rosmarin","Thymian","Parmesan","Balsamico"); beschreibung="Ausgewachsener brauner Champignon mit fleischiger Textur – ideal als Veggie-Burger."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Reishi"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("bitter","holzig","herb"); herkunft="Ostasien"; geschmack=@{acidity=0;sweetness=0;bitterness=5;umami=2;spiciness=0;saltiness=0}; pairings=@("Dashi","Honig","Ingwer","Schokolade"); beschreibung="Heilpilz mit intensiver Bitterkeit, meist getrocknet als Tee oder Pulver verwendet."; lagertemp="Trocken (getrocknet)"; einheit="Gramm" },
  @{ name="Samtfußrübling"; kategorie="Pilze"; saison=@("Winter","Frühling"); aromaprofil=@("mild","fruchtig","süßlich"); herkunft="Ostasien/Europa"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Sojasauce","Miso","Tofu","Dashi"); beschreibung="Kleiner goldener Pilz mit zartem, fruchtigem Aroma – Rohform des kultivierten Enoki."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Schwarzfußröhrling"; kategorie="Pilze"; saison=@("Sommer","Herbst"); aromaprofil=@("mild","nussig","fruchtig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=0}; pairings=@("Butter","Petersilie","Knoblauch","Ei"); beschreibung="Waldpilz mit feinem nussigem Aroma und zarter Textur, hält Hitze gut stand."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Semmelstoppelpilz"; kategorie="Pilze"; saison=@("Herbst"); aromaprofil=@("würzig","pfeffrig","fruchtig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=2;saltiness=0}; pairings=@("Sahne","Petersilie","Wildfleisch","Rosmarin"); beschreibung="Unterschätzter Herbstpilz mit leicht pfeffriger Note und kräftiger Textur."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Trüffelbutter"; kategorie="Pilze"; saison=@("Herbst","Winter"); aromaprofil=@("intensiv","erdig","nussig"); herkunft="Frankreich/Italien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=5;spiciness=0;saltiness=2}; pairings=@("Pasta","Ei","Risotto","Brioche"); beschreibung="Mit Schwarztrüffel aromatisierte Butter – ein Löffel reicht aus, um ein Gericht zu adeln."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Trüffelöl"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","erdnussig","trüffelig"); herkunft="Italien/Frankreich"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=4;spiciness=0;saltiness=0}; pairings=@("Pasta","Risotto","Ei","Kartoffelpüree"); beschreibung="Mit Trüffelaroma angereichertes Olivenöl – sparsam dosiert von größter Wirkung."; lagertemp="Raumtemperatur (dunkel)"; einheit="Gramm" },
  @{ name="Chaga"; kategorie="Pilze"; saison=@("Ganzjährig"); aromaprofil=@("erdig","vanillisch","mild bitter"); herkunft="Sibirien/Nordeuropa"; geschmack=@{acidity=0;sweetness=1;bitterness=3;umami=1;spiciness=0;saltiness=0}; pairings=@("Birke","Honig","Ingwer","Zimt"); beschreibung="Birkenparasit mit erdiger Vanillenote, als Tee oder Pulver in der Küche eingesetzt."; lagertemp="Trocken (getrocknet)"; einheit="Gramm" },
  @{ name="Brie de Meaux"; kategorie="Milchprodukte & Käse"; saison=@("Herbst","Winter"); aromaprofil=@("cremig","pilzartig","mild"); herkunft="Île-de-France, Frankreich"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=2}; pairings=@("Weintraube","Walnuss","Baguette","Apfel"); beschreibung="AOP-Weichkäse mit edlem Weißschimmelmantel und cremig schmelzendem Innenleben."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Camembert de Normandie"; kategorie="Milchprodukte & Käse"; saison=@("Herbst","Winter"); aromaprofil=@("pilzartig","cremig","leicht ammoniakisch"); herkunft="Normandie, Frankreich"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=2}; pairings=@("Apfelwein","Calvados","Apfel","Walnuss"); beschreibung="Normannischer Weichkäse mit ausgeprägtem Aroma, ideal gebacken oder mit Apfelkompott."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Roquefort"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("intensiv","würzig","schimmelkäseartig"); herkunft="Roquefort-sur-Soulzon, Frankreich"; geschmack=@{acidity=2;sweetness=0;bitterness=2;umami=4;spiciness=1;saltiness=4}; pairings=@("Birne","Walnuss","Honig","Portwein"); beschreibung="König der Blauschimmelkäse – intensive Würze, cremige Textur, AOC-geschützt seit 1925."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Gorgonzola"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("würzig","cremig","pikant"); herkunft="Lombardei, Italien"; geschmack=@{acidity=2;sweetness=1;bitterness=2;umami=4;spiciness=1;saltiness=3}; pairings=@("Birne","Walnuss","Honig","Risotto"); beschreibung="Legendärer Blauschimmelkäse – Dolce cremig-mild, Piccante intensiv-scharf."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Stilton"; kategorie="Milchprodukte & Käse"; saison=@("Herbst","Winter"); aromaprofil=@("würzig","komplex","nussig"); herkunft="Midlands, England"; geschmack=@{acidity=2;sweetness=1;bitterness=2;umami=4;spiciness=1;saltiness=3}; pairings=@("Portobello","Birne","Sellerie","Portwein"); beschreibung="Britischer Blauschimmelkäse mit nussigem Komplexität, klassisch zu Portwein."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Manchego"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("nussig","leicht herb","kompakt"); herkunft="La Mancha, Spanien"; geschmack=@{acidity=1;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=3}; pairings=@("Quitte","Jamón","Weintraube","Mandel"); beschreibung="Schafsmilchkäse aus La Mancha – je länger gereift, desto nussiger und würziger."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Taleggio"; kategorie="Milchprodukte & Käse"; saison=@("Herbst","Winter"); aromaprofil=@("würzig","cremig","mild"); herkunft="Lombardei, Italien"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=3}; pairings=@("Honig","Birne","Risotto","Polenta"); beschreibung="Rotschmieriger Weichkäse mit intensivem Geruch aber mild-cremigem Geschmack."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Halloumi"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("salzig","gummiartig","mild"); herkunft="Zypern"; geschmack=@{acidity=1;sweetness=0;bitterness=0;umami=2;spiciness=0;saltiness=4}; pairings=@("Wassermelone","Minze","Zitrone","Chili"); beschreibung="Zypriostischer Grill- und Bratenkäse der nicht schmilzt – außen knusprig, innen weich."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Feta"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("salzig","säuerlich","krümelig"); herkunft="Griechenland"; geschmack=@{acidity=3;sweetness=0;bitterness=1;umami=2;spiciness=0;saltiness=4}; pairings=@("Tomate","Olive","Gurke","Oregano"); beschreibung="Griechischer Schafsmilchkäse in Salzlake – salzig, krümelig und unverzichtbar im Horiatiki."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Gruyère"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("nussig","süßlich","komplex"); herkunft="Greyerzbezirk, Schweiz"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=4;spiciness=0;saltiness=2}; pairings=@("Fondüe","Zwiebel","Speck","Baguette"); beschreibung="Schweizer AOC-Hartkäse mit nussig-süßem Aroma, Basis des Fondue Fribourgeois."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Ziegenkäse frisch"; kategorie="Milchprodukte & Käse"; saison=@("Frühling","Sommer"); aromaprofil=@("frisch","säuerlich","leicht ziegig"); herkunft="Frankreich/Europa"; geschmack=@{acidity=3;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=2}; pairings=@("Honig","Thymian","Kirsche","Rucola"); beschreibung="Frischer Ziegenkäse mit charakteristisch säuerlicher Note und leichtem Ziegenduft."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Schafsmilchkäse"; kategorie="Milchprodukte & Käse"; saison=@("Frühling","Sommer"); aromaprofil=@("würzig","lanolinartig","mild"); herkunft="Mittelmeerraum"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=3}; pairings=@("Honig","Walnuss","Feige","Thymian"); beschreibung="Aromatischer Schafsmilchkäse mit charakteristischem Lanolin-Aroma und reicher Textur."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Stracciatella di Bufala"; kategorie="Milchprodukte & Käse"; saison=@("Frühling","Sommer"); aromaprofil=@("milchig","frisch","cremig"); herkunft="Apulien, Italien"; geschmack=@{acidity=2;sweetness=2;bitterness=0;umami=2;spiciness=0;saltiness=1}; pairings=@("Tomate","Basilikum","Trüffel","Prosciutto"); beschreibung="Innenleben der Burrata – intensive Mozzarella-Fäden in frischer Sahne."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Sahne"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("cremig","mild","buttrg"); herkunft="Europa"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Vanille","Schokolade","Beeren","Kaffee"); beschreibung="Schlagsahne mit min. 30% Fettgehalt – Basis für Saucen, Suppen und Desserts."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Schmand"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("mild-sauer","cremig","frisch"); herkunft="Deutschland/Osteuropa"; geschmack=@{acidity=3;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=1}; pairings=@("Kartoffel","Dill","Schnittlauch","Speck"); beschreibung="Sauerrahm mit 20-29% Fett – cremiger als Crème fraîche, milder als Saure Sahne."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Buttermilch"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("sauer","leicht cremig","frisch"); herkunft="Europa"; geschmack=@{acidity=4;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Kräuter","Gurke","Zwiebel","Kartoffel"); beschreibung="Säuerliches Nebenprodukt der Butterherstellung – ideal für Marinaden und Backwaren."; lagertemp="0–4 °C"; einheit="Milliliter" },
  @{ name="Ossau-Iraty"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("nussig","mild","butterartig"); herkunft="Baskenland/Béarn, Frankreich"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Kirschkonfitüre","Walnuss","Piment d'Espelette","Honig"); beschreibung="Baskinischer AOP-Schafskäse mit butterig-nussigem Profil, klassisch mit Kirschkonfitüre."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Époisses"; kategorie="Milchprodukte & Käse"; saison=@("Herbst","Winter"); aromaprofil=@("intensiv","würzig","cremig"); herkunft="Burgund, Frankreich"; geschmack=@{acidity=2;sweetness=1;bitterness=1;umami=4;spiciness=0;saltiness=3}; pairings=@("Burgunderwein","Senf","Brot","Trauben"); beschreibung="Legende des Burgunds – mit Marc de Bourgogne gewashene Rinde und intensivstem Aroma."; lagertemp="4–8 °C"; einheit="Gramm" },
  @{ name="Asiago"; kategorie="Milchprodukte & Käse"; saison=@("Ganzjährig"); aromaprofil=@("mild","süßlich","nussig"); herkunft="Venetien, Italien"; geschmack=@{acidity=1;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Speck","Feige","Honig","Birne"); beschreibung="Norditalienischer DOP-Käse – frisch mild, gereift nussig-intensiv."; lagertemp="4–8 °C"; einheit="Gramm" }
)
Insert-Batch $b4
