$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 3: Fisch & Meeresfrüchte (22) + Fleisch & Geflügel (18) = 40 items
$b3 = @(
  @{ name="Wolfsbarsch"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","zart","leicht süßlich"); herkunft="Mittelmeer/Atlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Fenchel","Kapern","Zitrone","Olivenöl"); beschreibung="Feinfleischiger Meeresfisch mit zartem, mildem Aroma, ideal gedämpft oder auf der Haut gebraten."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Dorade"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","nussig","süßlich"); herkunft="Mittelmeer"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Oliven","Tomate","Thymian","Zitrone"); beschreibung="Beliebter Mittelmeerbarsch mit festem, würzigem Fleisch und goldener Haut."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Rotbarbe"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("würzig","intensiv","meeresartig"); herkunft="Mittelmeer"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=3}; pairings=@("Oliven","Tomate","Kapern","Fenchel"); beschreibung="Leuchtend rot schimmernder Kleinfisch mit intensivem Meeresaroma und würziger Leber."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Seeteufel"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("fest","mild","hummerspähnlich"); herkunft="Nordatlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Chorizo","Kapern","Zitrone","Rosmarin"); beschreibung="Festfleischiger Tiefseefisch mit hummerspähnlicher Textur – hält starkes Anbraten aus."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Heilbutt"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","süßlich","fest"); herkunft="Nordatlantik"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Safran","Kapern","Zitronenbutter","Limette"); beschreibung="Großer Plattfisch mit festem, weißem Fleisch und eleganter, milder Geschmacknote."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Seezunge"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("delikat","buttrg","nussig"); herkunft="Nordsee/Atlantik"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Kapern","Butter","Zitrone","Petersilie"); beschreibung="Klassischer Edelfisch der französischen Küche – zart, delikat und ideal in Meunière."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Makrele"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer","Herbst"); aromaprofil=@("fettig","intensiv","würzig"); herkunft="Nordatlantik/Nordsee"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=3}; pairings=@("Senf","Rote Bete","Meerrettich","Apfel"); beschreibung="Fetter Meeresfisch mit intensivem Aroma, herrlich gegrillt oder als Räuchermakrele."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Sardine"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer"); aromaprofil=@("würzig","fettig","intensiv"); herkunft="Mittelmeer/Atlantik"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=5;spiciness=0;saltiness=3}; pairings=@("Zitrone","Olivenöl","Kapern","Tomate"); beschreibung="Kleiner Fetthering mit intensivem Umami-Geschmack, frisch vom Grill ein Hochgenuss."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Thunfisch"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer"); aromaprofil=@("fleischig","mild","Ozean"); herkunft="Atlantik/Pazifik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=2}; pairings=@("Sojasauce","Ingwer","Sesam","Wasabi"); beschreibung="Königsfisch des Ozeans – als Sashimi überragend, als Steak kaum zu übertreffen."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Schwertfisch"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer"); aromaprofil=@("fest","mild","leicht fleischig"); herkunft="Mittelmeer"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Kapern","Tomate","Zitrone","Olivenöl"); beschreibung="Festfleischiger Hochseefisch der sizilianischen Küche – als Steak gegrillt ideal."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Hummer"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer"); aromaprofil=@("süßlich","intensiv","nussig"); herkunft="Nordatlantik/Bretagne"; geschmack=@{acidity=0;sweetness=3;bitterness=0;umami=4;spiciness=0;saltiness=3}; pairings=@("Butter","Tarragon","Cognac","Crème fraîche"); beschreibung="Der König der Meeresfrüchte – süßes Fleisch mit nussiger Tiefe, unverzichtbar auf der Karte."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Garnele"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","jodhaltig","mild"); herkunft="Weltweit"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Knoblauch","Limette","Chili","Koriander"); beschreibung="Vielseitige Krustentiere mit süßem Jod-Aroma, vom Bisque bis zum Tempura."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Tintenfisch"; kategorie="Fisch & Meeresfrüchte"; saison=@("Sommer"); aromaprofil=@("mild","salzig","leicht süß"); herkunft="Mittelmeer"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Knoblauch","Petersilie","Zitrone","Chorizo"); beschreibung="Calamar mit zarter Textur wenn schnell gegart – langsam geschmort wird er ebenfalls wunderbar."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Oktopus"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("würzig","zart","Meeresfrüchte"); herkunft="Mittelmeer/Atlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=3}; pairings=@("Paprika","Olivenöl","Kapern","Zitrone"); beschreibung="Langsam geschmorter Oktopus mit butterweicher Textur und intensivem Meeresgeschmack."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Venusmuschel"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("salzig","jodhaltig","süßlich"); herkunft="Atlantik/Mittelmeer"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=4;spiciness=0;saltiness=4}; pairings=@("Weißwein","Knoblauch","Petersilie","Tomate"); beschreibung="Zarte Muscheln mit intensivem Meeresaroma, klassisch in Vongole-Pasta."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Miesmuschel"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter"); aromaprofil=@("salzig","jodhaltig","intensiv"); herkunft="Nordsee/Atlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=4}; pairings=@("Weißwein","Knoblauch","Crème fraîche","Zitrone"); beschreibung="Nordseeklassiker mit intensivem Jodaroma und saftigem Fleisch – Moules frites!"; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Herzmuschel"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter"); aromaprofil=@("intensiv salzig","jodhaltig","süßlich"); herkunft="Nordsee/Atlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=5}; pairings=@("Petersilie","Knoblauch","Zitrone","Weißwein"); beschreibung="Kleine Muscheln mit intensivem Meerescharakter, knackig und jodig."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Abalone"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","nussig","Meeresfrüchte"); herkunft="Japan/Australien"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=4;spiciness=0;saltiness=2}; pairings=@("Butter","Sake","Sojasauce","Ingwer"); beschreibung="Teuerste Meeresschnecke der Welt mit nussig-süßem Fleisch und einzigartiger Textur."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Lachs"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("fettig","mild","nussig"); herkunft="Nordatlantik/Pazifik"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=3;spiciness=0;saltiness=2}; pairings=@("Dill","Meerrettich","Zitronen","Crème fraîche"); beschreibung="Der meistgegessene Edelpelagier – von roh bis Beize zu Sous-vide perfekt vielseitig."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Flunder"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter","Frühling"); aromaprofil=@("mild","zart","leicht nussig"); herkunft="Nordsee"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=2;spiciness=0;saltiness=2}; pairings=@("Butter","Kapern","Petersilie","Zitrone"); beschreibung="Zarter Nordsee-Plattfisch mit mildem Aroma, traditionell in Butter geschwenkt."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Seelachs"; kategorie="Fisch & Meeresfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","fest","neutral"); herkunft="Nordatlantik"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=2;spiciness=0;saltiness=2}; pairings=@("Senf","Dill","Meerrettich","Kartoffel"); beschreibung="Fester Weißfisch mit neutralem Profil – nimmt starke Aromen gut auf."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Ikura"; kategorie="Fisch & Meeresfrüchte"; saison=@("Herbst","Winter"); aromaprofil=@("salzig","jodhaltig","fischig","umami"); herkunft="Japan/Russland"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=5;spiciness=0;saltiness=4}; pairings=@("Sojasauce","Frischkäse","Gurke","Sake"); beschreibung="Lachskaviar mit charakteristischem Knacken und explosivem Salzjod-Umami-Profil."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Rinderbäckchen"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("reichhaltig","fleischig","gelatinös"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=5;spiciness=0;saltiness=1}; pairings=@("Rotwein","Sellerie","Karotte","Thymian"); beschreibung="Langsam geschmorte Rinderbäckchen entwickeln butterweiches Fleisch und reichhaltige Gelatine."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Ochsenschwanz"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("tief","würzig","gelatinös"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=5;spiciness=0;saltiness=1}; pairings=@("Rotwein","Tomate","Lauch","Karotte"); beschreibung="Gelatinereicher Schmorfleischklassiker mit tiefem Rindfleischaroma und kollagenreicher Sauce."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Knochenmark"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("buttrg","reichhaltig","nussig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Petersilie","Kapern","Röstbrot","Fleur de Sel"); beschreibung="Gebratenes Knochenmark – butterreich und tief im Geschmack, auf geröstetem Brot ein Klassiker."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Lammkeule"; kategorie="Fleisch"; saison=@("Frühling","Herbst"); aromaprofil=@("würzig","mild","aromatisch"); herkunft="Frankreich/Griechenland"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Rosmarin","Knoblauch","Anchovis","Rotwein"); beschreibung="Klassischer Sonntagsbraten mit aromatischem Lammfleisch, langsam mit Kräutern gegart."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Lammhaxe"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("würzig","tief","gelatinös"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Rosmarin","Thymian","Knoblauch","Rotwein"); beschreibung="Geschmorte Haxe mit zart fallendem Fleisch und intensiver, kollagenreicher Sauce."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Kaninchen"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("mild","leicht nussig","zart"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Senf","Thymian","Speck","Weißwein"); beschreibung="Zartes, leicht nussiges Wildtier-Fleisch – ideal als Confit oder in Senfrahm."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Wildschein"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("wild","würzig","erdnussig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=4;spiciness=0;saltiness=1}; pairings=@("Wacholder","Rotwein","Preiselbeere","Sellerie"); beschreibung="Kräftiges Wildfleisch mit typisch würziger Wildnote und tiefer Karamellnuance."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Reh"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("zart","mild","würzig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Preiselbeere","Wacholder","Rotwein","Sellerie"); beschreibung="Das zarteste aller Wildtiere – Rehrücken medium gebraten ist ein Herbstklassiker."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Hirsch"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("kräftig","würzig","nussig"); herkunft="Europa/Nordamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=4;spiciness=0;saltiness=1}; pairings=@("Wacholder","Preiselbeere","Schokolade","Rotwein"); beschreibung="Kraftvolles Rotwildfleisch mit ausgeprägtem Wildgeschmack – ideal mit Wacholder."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Wachtel"; kategorie="Fleisch"; saison=@("Herbst"); aromaprofil=@("zart","aromatisch","mild"); herkunft="Europa/Asien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Feige","Speck","Foie Gras","Thymian"); beschreibung="Kleines Federwild mit zartem Fleisch und feinem Aroma – ideal gefüllt oder konfiert."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Fasan"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("wild","aromatisch","nussig"); herkunft="Asien/Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=1}; pairings=@("Preiselbeere","Kohl","Speck","Wacholderbeere"); beschreibung="Klassisches Federvieh mit ausgeprägterem Wildgeschmack als Hähnchen."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Perlhuhn"; kategorie="Fleisch"; saison=@("Ganzjährig"); aromaprofil=@("würzig","leicht wild","aromatisch"); herkunft="Afrika/Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Rosmarin","Thymian","Zitrone","Lavendel"); beschreibung="Zwischen Huhn und Fasan angesiedelt – aromatischer als Hähnchen, weniger wild als Fasan."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Foie Gras"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("buttrig","reich","nussig"); herkunft="Frankreich"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=4;spiciness=0;saltiness=1}; pairings=@("Feige","Sauternes","Brioche","Trüffel"); beschreibung="Gänsestopfleber mit seidenartig-buttrigem Schmelz und unvergleichlichem Reichtum."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Zicklein"; kategorie="Fleisch"; saison=@("Frühling"); aromaprofil=@("mild","zart","leicht würzig"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=1}; pairings=@("Rosmarin","Knoblauch","Zitrone","Kapern"); beschreibung="Zartes Jungziegenlamm – Frühlingsdelikatesse der mediterranen Küche."; lagertemp="0–2 °C"; einheit="Gramm" },
  @{ name="Hase"; kategorie="Fleisch"; saison=@("Herbst","Winter"); aromaprofil=@("wild","würzig","tief"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=4;spiciness=0;saltiness=1}; pairings=@("Thymian","Rotwein","Preiselbeere","Wacholder"); beschreibung="Wildhase mit intensiverem Geschmack als Hauskaninchen, klassisch in Hasenpfeffer."; lagertemp="0–2 °C"; einheit="Gramm" }
)
Insert-Batch $b3
