$key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWRzaHN1cWdoc2lhZWZwaXRrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTg1NTYxMiwiZXhwIjoyMDk3NDMxNjEyfQ.8D3LbUjntlKIdUxADVZkdwOXZNvqWhY5SXUAblOA5b8"
$url = "https://bredshsuqghsiaefpitk.supabase.co/rest/v1/zutaten"
$headers = @{ "apikey" = $key; "Authorization" = "Bearer $key"; "Content-Type" = "application/json"; "Prefer" = "return=minimal" }

function Insert-Batch($items) {
  $json = $items | ConvertTo-Json -Depth 6 -Compress
  try {
    $r = Invoke-WebRequest -Uri $url -Method POST -Headers $headers -Body $json -UseBasicParsing
    Write-Output "OK $($r.StatusCode) - $($items.Count) items"
  } catch {
    Write-Output "ERR: $_"
  }
}

# BATCH 7: Getreide, Hülsenfrüchte & Nüsse (45 items)
$b7 = @(
  @{ name="Farro"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","süßlich","leicht würzig"); herkunft="Toskana/Umbrien, Italien"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Pilze","Tomaten","Parmesan","Kräuter"); beschreibung="Urkorn der Römer mit nussigem Biss und großartiger Textur – besser als Risottoreis für Körnergerichte."; lagertemp="Trocken (luftdicht)"; einheit="Gramm" },
  @{ name="Teff"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","leicht malzig","erdig"); herkunft="Äthiopien/Eritrea"; geschmack=@{acidity=1;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Injera","Kokosmilch","Honig","Schokolade"); beschreibung="Kleinst-Urgetreide aus Äthiopien – Basis des Injera-Fladenbrots, glutenfrei und proteinreich."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Amaranth"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("erdig","mild","grasig"); herkunft="Mexiko/Zentralamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Beeren","Banane","Honig","Milch"); beschreibung="Präkolumbianisches Pseudogetreide mit erdiger Note und vollständigem Aminosäure-Profil."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Freekeh"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("rauchig","nussig","grasig"); herkunft="Levante/Ägypten"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Lamm","Hühnchen","Kräuter","Jogurt"); beschreibung="Grüner gerösteter Weizen mit einzigartigem Raucharoma – der modernste Altkorn."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Sorghum"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht süßlich","neutral"); herkunft="Afrika/Asien"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("BBQ","Kokos","Linsen","Joghurt"); beschreibung="Widerstandsfähiges Urgetreide mit mildem Geschmack, glutenfrei und vielseitig einsetzbar."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Dinkel"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Herbst"); aromaprofil=@("nussig","leicht süßlich","kräuterig"); herkunft="Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Pilze","Kräuter","Nüsse","Honig"); beschreibung="Urzorn mit besserem Nährwert als Weizen und nussigem Geschmack – Rückkehr in die Küche."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Emmer"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Herbst"); aromaprofil=@("nussig","würzig","mild"); herkunft="Naher Osten/Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Pilze","Bohnen","Tomaten","Olivenöl"); beschreibung="Vorfahre des modernen Weizens – bissfest, nussig, großartig als Körner-Salat."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Hirse"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Herbst"); aromaprofil=@("mild","leicht nussig","neutral"); herkunft="Afrika/Asien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Kokosmilch","Gemüse","Kräuter","Joghurt"); beschreibung="Glutenfreies Urgetreide mit mildem Aroma – aufgequollen zu einer fluffigen, vielseitigen Basis."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Bulgur"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","mild","weizenartig"); herkunft="Naher Osten"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Petersilie","Tomate","Minze","Zitrone"); beschreibung="Vorgegarter Weizen in diversen Feinheitsstufen – Basis des Tabbouleh, schnell zubereitet."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Couscous"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht nussig","neutral"); herkunft="Nordafrika/Maghreb"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Lamm","Zucchini","Kichererbse","Ras el Hanout"); beschreibung="Gedämpfter Hartweizengrieß – Nordafrikas Pasta, Basis unzähliger Tajine-Begleitungen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Lupine"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Sommer"); aromaprofil=@("nussig","mild bitter","proteinreich"); herkunft="Mittelmeerraum/Südamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Olivenöl","Zitrone","Kräuter","Tomaten"); beschreibung="Europäische Proteinpflanze mit nussigem Profil – als Mehl oder Bohne ein nachhaltige Alternative."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Edamame"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Sommer"); aromaprofil=@("frisch","mild süßlich","grasig"); herkunft="Japan/China"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Sojasauce","Sesam","Wasabi","Miso"); beschreibung="Junge Sojabohnen in der Schote – frisch und knackig, ideal als proteinreicher Snack."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Schwarze Bohne"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("erdig","mild","leicht metallisch"); herkunft="Mittelamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=0}; pairings=@("Chili","Koriander","Limette","Reis"); beschreibung="Cremige schwarze Bohne der lateinamerikanischen Küche – herrlich in Eintöpfen oder Tacos."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Adzuki"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Herbst"); aromaprofil=@("süßlich","mild","nussig"); herkunft="Japan/China"; geschmack=@{acidity=0;sweetness=3;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Klebreis","Kokos","Sesam","Anko"); beschreibung="Kleine rote Bohne, Symbol der japanischen Süßwaren – Basis der Anko-Paste in Wagashi."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Mungobohne"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","leicht grasig","frisch (gekeimt)"); herkunft="Indien/Südostasien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Ingwer","Knoblauch","Kokosmilch","Curry"); beschreibung="Kleine grüne Bohne – vielseitig als Dal oder gekeimt als knackige Sprossenunterlage."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Belugalinse"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("erdig","mild","fest"); herkunft="Europa/Kanada"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=0;saltiness=0}; pairings=@("Ziegenkäse","Walnuss","Rotweinessig","Kräuter"); beschreibung="Schwarze Belugalinse mit fester Textur und erdiger Note – behält Form beim Garen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Puy-Linse"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("pfeffrig","erdig","nussig"); herkunft="Le Puy, Frankreich"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=3;spiciness=1;saltiness=0}; pairings=@("Speck","Senf","Kräuter","Vinaigrette"); beschreibung="AOP-Linse aus Le Puy mit charakteristisch pfeffrigem Biss – die Königin der Linsen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Kichererbse"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","cremig","mild"); herkunft="Naher Osten/Nordafrika"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=3;spiciness=0;saltiness=0}; pairings=@("Tahini","Zitrone","Knoblauch","Cumin"); beschreibung="Vielseitige Hülsenfrucht – als Hummus, Falafel oder geröstet ein Küchenmuss."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Fava-Bohne"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Frühling","Sommer"); aromaprofil=@("süßlich","frisch","leicht herb"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=2;bitterness=2;umami=2;spiciness=0;saltiness=0}; pairings=@("Olivenöl","Minze","Pecorino","Zitrone"); beschreibung="Ackerbohne – jung und frisch ein Frühlingsereignis, doppelt enthülst und in Olivenöl wunderbar."; lagertemp="0–4 °C (frisch)"; einheit="Gramm" },
  @{ name="Weiße Bohne"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("cremig","mild","buttrig"); herkunft="Mittelamerika/Mittelmeer"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Rosmarin","Thymian","Knoblauch","Olivenöl"); beschreibung="Cremige Cannellini oder Borlotti – Basis des Cassoulet und Toskana-Eintöpfe."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Paranuss"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("cremig","mild","leicht seifig"); herkunft="Amazonas, Brasilien"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Schokolade","Kokosnuss","Mango","Vanille"); beschreibung="Großnuss aus dem Amazonas mit cremig-mildem Profil und außergewöhnlichem Selengehalt."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Macadamia"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("sehr cremig","buttrig","mild süßlich"); herkunft="Australien/Hawaii"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Weißschokolade","Kokos","Ananas","Vanille"); beschreibung="Reichste Nuss der Welt im Fettgehalt – buttrig-cremig und schwer zu knacken."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Cashew"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("mild","buttrig","leicht süßlich"); herkunft="Brasilien/Westafrika/Indien"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Currygerichte","Schokolade","Kokosmilch","Stir Fry"); beschreibung="Mild-cremige Nuss – roh oder geröstet essbar, als Paste hervorragend in veganen Saucen."; lagertemp="Trocken (kühl)"; einheit="Gramm" },
  @{ name="Pekannuss"; kategorie="Nüsse & Samen"; saison=@("Herbst"); aromaprofil=@("buttrig","süßlich","nussig"); herkunft="Nordamerika"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Ahornsirup","Schokolade","Bourbon","Honig"); beschreibung="Süßliche amerikanische Nuss mit butterigem Profil – essentiell im Pecan Pie."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Tigernuss"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("süßlich","nussig","kokosähnlich"); herkunft="Westafrika/Spanien"; geschmack=@{acidity=0;sweetness=3;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Horchata","Vanille","Kokos","Datteln"); beschreibung="Kleine Knollensedge mit kokosartigem Süßprofil – Basis der spanischen Horchata."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Lotussamen"; kategorie="Nüsse & Samen"; saison=@("Sommer"); aromaprofil=@("mild","leicht nussig","stärkehaltig"); herkunft="Ostasien"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Klebreis","Jujube","Lychee","Zucker"); beschreibung="Samen der Lotospflanze – in der asiatischen Dessertküche unverzichtbar, frisch oder getrocknet."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Mohn"; kategorie="Nüsse & Samen"; saison=@("Sommer"); aromaprofil=@("nussig","mild","leicht bitter"); herkunft="Mittelmeerraum/Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=2;umami=1;spiciness=0;saltiness=0}; pairings=@("Zitrone","Honig","Butter","Vanille"); beschreibung="Kleiner blauer Same mit nussigem Profil – geröstet für Backwaren und Nudelgerichte."; lagertemp="Trocken (dunkel)"; einheit="Gramm" },
  @{ name="Leinsamen"; kategorie="Nüsse & Samen"; saison=@("Herbst"); aromaprofil=@("mild","nussig","grasig"); herkunft="Europa/Kanada"; geschmack=@{acidity=0;sweetness=0;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Joghurt","Müsli","Smoothie","Brot"); beschreibung="Omega-3-reiche Same mit mildem Profil – geschrotet besser verdaubar und nussiger."; lagertemp="Trocken (dunkel)"; einheit="Gramm" },
  @{ name="Sonnenblumenkern"; kategorie="Nüsse & Samen"; saison=@("Herbst"); aromaprofil=@("mild","nussig","leicht ölig"); herkunft="Osteuropa/Nordamerika"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Salat","Brot","Joghurt","Tahini"); beschreibung="Geröstet intensiviert sich das nussige Aroma – vielseitig in Salaten und Backwaren."; lagertemp="Trocken (dunkel)"; einheit="Gramm" },
  @{ name="Hanfsamen"; kategorie="Nüsse & Samen"; saison=@("Herbst"); aromaprofil=@("nussig","mild","grünlich"); herkunft="Europa/Kanada"; geschmack=@{acidity=0;sweetness=1;bitterness=1;umami=2;spiciness=0;saltiness=0}; pairings=@("Salat","Smoothie","Joghurt","Müsli"); beschreibung="Proteinreiche Samen mit mildem, nussigem Geschmack und vollständigem Aminosäureprofil."; lagertemp="0–4 °C (nach Öffnung)"; einheit="Gramm" },
  @{ name="Chiasamen"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("neutral","mild","leicht nussig"); herkunft="Mexiko/Guatemala"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Joghurt","Kokosmilch","Beeren","Avocado"); beschreibung="Gelbildende Samen mit neutralem Geschmack – Texturgeber für Puddings und Smoothies."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Pinienkern geröstet"; kategorie="Nüsse & Samen"; saison=@("Herbst"); aromaprofil=@("intensiv nussig","buttrg","aromatisch"); herkunft="Mittelmeerraum"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=2;spiciness=0;saltiness=0}; pairings=@("Rucola","Basilikum","Parmesan","Spinat"); beschreibung="Trocken geröstet entfalten Pinienkerne erst ihre volle nussige Intensität."; lagertemp="0–4 °C (nach Rösten)"; einheit="Gramm" },
  @{ name="Tahinipaste"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("intensiv nussig","bitter","sesamartig"); herkunft="Naher Osten"; geschmack=@{acidity=0;sweetness=0;bitterness=3;umami=2;spiciness=0;saltiness=1}; pairings=@("Hummus","Zitrone","Knoblauch","Datteln"); beschreibung="Gemahlene Sesampaste – Basis von Hummus und Baba Ghanoush mit intensiver Sesamtiefe."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Mandelbutter"; kategorie="Nüsse & Samen"; saison=@("Ganzjährig"); aromaprofil=@("cremig","mild nussig","süßlich"); herkunft="Mittelmeer/Kalifornien"; geschmack=@{acidity=0;sweetness=2;bitterness=1;umami=1;spiciness=0;saltiness=0}; pairings=@("Banane","Schokolade","Apfel","Haferflocken"); beschreibung="Gemahlene Mandelpaste – cremig-nussig, herrlich in Saucen und als gesunder Brotaufstrich."; lagertemp="0–4 °C"; einheit="Gramm" },
  @{ name="Fleur de Sel"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Sommer"); aromaprofil=@("mineralisch","salzig","mild"); herkunft="Guérande/Camargue, Frankreich"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=1;spiciness=0;saltiness=5}; pairings=@("Schokolade","Karamell","Butter","Steak"); beschreibung="Handabgeschöpfte Meersalzblüte – feuchtes, mineralisches Finishing-Salz der Haute Cuisine."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Schwarzes Salz (Kala Namak)"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("schwefelartig","eigenartig","ei-ähnlich"); herkunft="Nordindien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=2;spiciness=0;saltiness=4}; pairings=@("Chaat","Raita","Tofu-Ei","Chutneys"); beschreibung="Vulkanisches Indien-Salz mit überraschendem Eidotter-Aroma durch Schwefelverbindungen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Maldon Salz"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("salzig","mineralisch","leicht mild"); herkunft="Essex, England"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=1;spiciness=0;saltiness=5}; pairings=@("Schokolade","Steak","Caramel","Dessert"); beschreibung="Pyramidenförmige Salzflocken mit angenehm mildem, runden Salzgeschmack – perfekt zum Finishen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Trüffelsalz"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("intensiv trüffelartig","salzig","erdig"); herkunft="Italien/Frankreich"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=4;spiciness=0;saltiness=4}; pairings=@("Pasta","Ei","Kartoffelpüree","Steak"); beschreibung="Meersalz aromatisiert mit getrocknetem Trüffel – ein Löffel hebt jedes Gericht an."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Sushireis"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("mild","klebrig","reinartig"); herkunft="Japan"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Nori","Fisch","Reisessig","Mirin"); beschreibung="Spezieller Rundkornreis mit hohem Stärkegehalt – gewürzt der Schlüssel zu perfektem Sushi."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Jasminreis"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("duftig","blumig","mild"); herkunft="Thailand"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Curry","Kokos","Hühnchen","Garnelen"); beschreibung="Duftender Langkornreis aus Thailand mit angenehm blumigem Aroma beim Kochen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Basmati"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","duftig","aromatisch"); herkunft="Nordindien/Pakistan"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Curry","Biriyani","Lamm","Joghurt"); beschreibung="König der Langreis-Sorten – nussiges Aroma und fluffige Trennung der Körner nach dem Garen."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Reismehl"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("neutral","leicht süßlich","mild"); herkunft="Asien/Europa"; geschmack=@{acidity=0;sweetness=1;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Tempura","Crepes","Mochi","Noodles"); beschreibung="Glutenfreies Feinmehl aus Reis – unverzichtbar für knusprige Tempura-Panade und Mochi."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Tapiokastärke"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("neutral","geschmacklos","bindefähig"); herkunft="Südamerika/Asien"; geschmack=@{acidity=0;sweetness=0;bitterness=0;umami=0;spiciness=0;saltiness=0}; pairings=@("Kokosmilch","Milch","Fruchtsaucen","Pudding"); beschreibung="Stärke aus Maniok – bindet klarer als Maisstärke, ideal für Blasenpuddinge und Perlen-Tees."; lagertemp="Trocken"; einheit="Gramm" },
  @{ name="Polenta Bramata"; kategorie="Getreide & Hülsenfrüchte"; saison=@("Ganzjährig"); aromaprofil=@("nussig","süßlich","maiskräftig"); herkunft="Norditalien"; geschmack=@{acidity=0;sweetness=2;bitterness=0;umami=1;spiciness=0;saltiness=0}; pairings=@("Pilze","Parmesan","Ragù","Rosmarin"); beschreibung="Grober Maisgrieß der alpenländischen Küche – langsam gerührt cremig, abgekühlt röstbar."; lagertemp="Trocken"; einheit="Gramm" }
)
Insert-Batch $b7
