import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-admin';
import { getRequestUser } from '@/lib/get-request-user';
import { ADMIN_EMAIL } from '@/config/roles';

const MEHR_ZUTATEN = [
  // ── KLASSISCHES GEMÜSE & SALAT ──────────────────────────────────────────────
  {
    name: 'Karotte', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter', 'Frühling'], herkunft: 'Europa',
    aromaprofil: ['süß', 'erdig', 'mild'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Ingwer', 'Kreuzkümmel', 'Orange', 'Koriander', 'Butter'],
    beschreibung: 'Vielseitiges Wurzelgemüse – roh, gekocht, fermentiert oder als Creme. Süße steigt beim Rösten.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Sellerie', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['würzig', 'erdig', 'nussig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 2, umami: 3, spiciness: 1, saltiness: 1 },
    pairings: ['Trüffel', 'Apfel', 'Haselnuss', 'Blauschimmelkäse', 'Walnuss'],
    beschreibung: 'Knollensellerie ist ein Allrounder – als Pürée, Chip, Carpaccio oder Fond-Basis ideal.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Lauch', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter', 'Frühling'], herkunft: 'Europa',
    aromaprofil: ['mild', 'zwiebelartig', 'süß'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 2, spiciness: 1, saltiness: 0 },
    pairings: ['Butter', 'Crème fraîche', 'Jakobsmuschel', 'Käse', 'Thymian'],
    beschreibung: 'Milder als Zwiebel, vielseitig einsetzbar – als Vinaigrette, confiert oder als Röstgemüse.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Zwiebel', kategorie: 'Gemüse',
    saison: ['Ganzjährig'], herkunft: 'Weltweilt',
    aromaprofil: ['scharf', 'süß (geröstet)', 'würzig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 3, spiciness: 2, saltiness: 0 },
    pairings: ['Fleisch', 'Käse', 'Essig', 'Kräuter', 'Wein'],
    beschreibung: 'Basis der meisten Küchen der Welt. Roh scharf, karamellisiert süß und tief-umami.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Schalotte', kategorie: 'Gemüse',
    saison: ['Ganzjährig'], herkunft: 'Frankreich',
    aromaprofil: ['mild', 'süß', 'fein-würzig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 3, spiciness: 1, saltiness: 0 },
    pairings: ['Rotwein', 'Butter', 'Fisch', 'Vinaigrette', 'Foie Gras'],
    beschreibung: 'Eleganter als Zwiebel – Grundlage für Beurre blanc, Saucen und feine Vinaigretten.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Knoblauch', kategorie: 'Gemüse',
    saison: ['Ganzjährig'], herkunft: 'Zentralasien',
    aromaprofil: ['scharf', 'würzig', 'intensiv'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 4, spiciness: 3, saltiness: 0 },
    pairings: ['Olivenöl', 'Tomaten', 'Fleisch', 'Kräuter', 'Butter'],
    beschreibung: 'Roh intensiv-scharf, confiert mild und süß, geröstet tief-karamellisch. Unverzichtbar.',
    lagertemp: '10–15°C', einheit: 'Gramm',
  },
  {
    name: 'Ingwer', kategorie: 'Gewürze & Kräuter',
    saison: ['Ganzjährig'], herkunft: 'Südostasien',
    aromaprofil: ['scharf', 'frisch', 'zitrusartig', 'würzig'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 1, umami: 1, spiciness: 4, saltiness: 0 },
    pairings: ['Karotte', 'Mango', 'Sojasauce', 'Limette', 'Kokos'],
    beschreibung: 'Frischer Ingwer ist aromatisch-scharf, getrockneter wärmer. Vielseitig in Asia- und Patisserie-Küche.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Kartoffel', kategorie: 'Gemüse',
    saison: ['Sommer', 'Herbst', 'Winter'], herkunft: 'Südamerika',
    aromaprofil: ['stärkehaltig', 'erdig', 'mild', 'nussig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Butter', 'Sahne', 'Trüffel', 'Kaviar', 'Schnittlauch'],
    beschreibung: 'Das universelle Comfort-Gemüse – als Pürée, Rösti, Chip oder Gnocchi jede Küche prägend.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Süßkartoffel', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Amerika',
    aromaprofil: ['süß', 'stärkehaltig', 'karamellisch'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Chili', 'Limette', 'Misopaste', 'Koriander', 'Kokos'],
    beschreibung: 'Süß und sättigend – als Pürée, geröstet oder als Velouté. Gut für süß-saure Kontraste.',
    lagertemp: '12–16°C', einheit: 'Gramm',
  },
  {
    name: 'Zucchini', kategorie: 'Gemüse',
    saison: ['Sommer'], herkunft: 'Italien',
    aromaprofil: ['mild', 'frisch', 'leicht-süß'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Olivenöl', 'Minze', 'Zitrone', 'Parmesan', 'Basilikum'],
    beschreibung: 'Leicht und vielseitig – roh als Carpaccio, gegrillt, frittiert oder als Blüte gefüllt.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Aubergine', kategorie: 'Gemüse',
    saison: ['Sommer', 'Herbst'], herkunft: 'Asien',
    aromaprofil: ['fleischig', 'rauchig', 'mild-bitter'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Tahini', 'Tomaten', 'Miso', 'Knoblauch', 'Lammfleisch'],
    beschreibung: 'Geröstet oder gegrillt entfaltet sie tiefes Raucharoma – Basis für Babaganoush und Caponata.',
    lagertemp: '10–12°C', einheit: 'Gramm',
  },
  {
    name: 'Paprika (rot)', kategorie: 'Gemüse',
    saison: ['Sommer', 'Herbst'], herkunft: 'Südamerika',
    aromaprofil: ['süß', 'fruchtig', 'mild'],
    geschmack: { acidity: 2, sweetness: 4, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Feta', 'Mandel', 'Chorizo', 'Knoblauch', 'Olivenöl'],
    beschreibung: 'Geröstet und gehäutet besonders süß – als Pürée, Romesco-Sauce oder confiert als Beilage.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Tomate', kategorie: 'Gemüse',
    saison: ['Sommer'], herkunft: 'Südamerika',
    aromaprofil: ['säuerlich', 'süß', 'fruchtig', 'umami'],
    geschmack: { acidity: 3, sweetness: 3, bitterness: 1, umami: 4, spiciness: 0, saltiness: 0 },
    pairings: ['Basilikum', 'Mozzarella', 'Olivenöl', 'Sardellen', 'Knoblauch'],
    beschreibung: 'Roh als Salat, konzentriert als Sugo oder confiert – Umami-Bombe der Sommerküche.',
    lagertemp: '18–22°C', einheit: 'Gramm',
  },
  {
    name: 'Gurke', kategorie: 'Gemüse',
    saison: ['Sommer'], herkunft: 'Südasien',
    aromaprofil: ['frisch', 'wässrig', 'mild', 'leicht-bitter'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Dill', 'Joghurt', 'Limette', 'Wasabi', 'Lachs'],
    beschreibung: 'Roh knackig-frisch, eingelegt komplex. Idealer Kontrast zu reichhaltigen Gerichten.',
    lagertemp: '10–12°C', einheit: 'Gramm',
  },
  {
    name: 'Radieschen', kategorie: 'Gemüse',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['scharf', 'frisch', 'pfeffrig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 1, spiciness: 3, saltiness: 0 },
    pairings: ['Butter', 'Fleur de Sel', 'Baguette', 'Schnittlauch', 'Forelle'],
    beschreibung: 'Klassisch mit Butter und Salz – perfekt als Garnitur, fermentiert oder in Vinaigretten.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Grüner Spargel', kategorie: 'Gemüse',
    saison: ['Frühling'], herkunft: 'Europa',
    aromaprofil: ['grasig', 'frisch', 'leicht-bitter', 'mineralisch'],
    geschmack: { acidity: 2, sweetness: 2, bitterness: 2, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Ei', 'Parmesan', 'Zitrone', 'Olivenöl', 'Prosciutto'],
    beschreibung: 'Intensiver als weißer Spargel – gegrillt, blanchiert oder als Risotto-Einlage.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Rucola', kategorie: 'Gemüse',
    saison: ['Frühling', 'Herbst'], herkunft: 'Mittelmeer',
    aromaprofil: ['scharf', 'pfeffrig', 'bitter', 'nussig'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 3, umami: 1, spiciness: 3, saltiness: 0 },
    pairings: ['Parmesan', 'Tomate', 'Zitrone', 'Olivenöl', 'Rinderfilet'],
    beschreibung: 'Scharfes Blattgemüse – Frische in Salaten, auf Pizza oder als Pesto-Alternative.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Spinat', kategorie: 'Gemüse',
    saison: ['Frühling', 'Herbst'], herkunft: 'Persien',
    aromaprofil: ['mild', 'erdig', 'mineralisch'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Parmesan', 'Ei', 'Muskat', 'Butter', 'Zitrone'],
    beschreibung: 'Blanchiert und ausgedrückt vielseitig – als Bett, Pürée, Pasta-Füllung oder Velouté.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Chicorée', kategorie: 'Gemüse',
    saison: ['Winter', 'Frühling'], herkunft: 'Belgien',
    aromaprofil: ['bitter', 'mild', 'leicht-süß (gegrillt)'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 4, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Blauschimmelkäse', 'Walnuss', 'Orange', 'Birne', 'Speck'],
    beschreibung: 'Bittere Eleganz – roh mit fruchtigen Elementen oder konfiert mit Honig ausbalanciert.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Avocado', kategorie: 'Gemüse',
    saison: ['Ganzjährig'], herkunft: 'Mexiko',
    aromaprofil: ['buttig', 'mild', 'nussig', 'cremig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Limette', 'Koriander', 'Chili', 'Meeresfrüchte', 'Tomatillo'],
    beschreibung: 'Cremig-mild – als Mousse, Tartare-Bett, Guacamole oder rohe Scheibe mit Meeresfrüchten.',
    lagertemp: '12–16°C', einheit: 'Gramm',
  },
  {
    name: 'Brokkoli', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter', 'Frühling'], herkunft: 'Mittelmeer',
    aromaprofil: ['grasig', 'leicht-bitter', 'mineralisch', 'nussig (geröstet)'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Parmesan', 'Sardellen', 'Knoblauch', 'Zitrone', 'Tahini'],
    beschreibung: 'Unterschätztes Gemüse – geröstet nussig und karamellisch, als Creme mit Texturen elegant.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Blumenkohl', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Mittelmeer',
    aromaprofil: ['mild', 'nussig', 'leicht-süß', 'erdig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Curry', 'Mandeln', 'Kapern', 'Rosinen', 'Butter brun'],
    beschreibung: 'Als Steak, Ganzes in Butter geröstet oder Creme – vielseitiger Allrounder der Herbstküche.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── OBST ─────────────────────────────────────────────────────────────────────
  {
    name: 'Apfel', kategorie: 'Obst',
    saison: ['Herbst', 'Winter'], herkunft: 'Deutschland',
    aromaprofil: ['säuerlich', 'süß', 'frisch', 'fruchtig'],
    geschmack: { acidity: 3, sweetness: 4, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Zimt', 'Calvados', 'Käse', 'Walnuss', 'Foie Gras'],
    beschreibung: 'Von säuerlich-knackig bis mehlig-süß – in Tarte, Chutney, Jus oder roh als Kontrast.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Birne', kategorie: 'Obst',
    saison: ['Herbst'], herkunft: 'Europa',
    aromaprofil: ['süß', 'blumig', 'mild', 'butterartig'],
    geschmack: { acidity: 2, sweetness: 4, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Blauschimmelkäse', 'Walnuss', 'Rotwein', 'Zimt', 'Schokolade'],
    beschreibung: 'Zart-süße Eleganz – pochiert in Rotwein, als Tarte oder roh mit Käse und Walnuss.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Quitte', kategorie: 'Obst',
    saison: ['Herbst'], herkunft: 'Kaukasus',
    aromaprofil: ['blumig', 'herb', 'honigartig', 'tanninreich'],
    geschmack: { acidity: 3, sweetness: 2, bitterness: 2, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Wildfleisch', 'Lamm', 'Käse', 'Vanille', 'Zimt'],
    beschreibung: 'Roh ungenießbar, gekocht ein Juwel – als Gelee, Paste oder pochiert zu Wild und Käse.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Erdbeere', kategorie: 'Obst',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['süß', 'fruchtig', 'leicht-säuerlich', 'florals'],
    geschmack: { acidity: 3, sweetness: 4, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Basilikum', 'Balsamico', 'Sahne', 'Vanille', 'Rhabarber'],
    beschreibung: 'Ikone des Frühlings – roh am aromatischsten, kurz mazeriert tiefer. Balsamico hebt das Aroma.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Himbeere', kategorie: 'Obst',
    saison: ['Sommer'], herkunft: 'Europa',
    aromaprofil: ['fruchtig', 'säuerlich', 'blumig', 'intensiv'],
    geschmack: { acidity: 4, sweetness: 3, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Schokolade', 'Rose', 'Lychee', 'Sahne', 'Pistazie'],
    beschreibung: 'Intensive Fruchtigkeit – als Coulis, Sorbet oder roh. Excellent mit Schokolade und Creme.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Kirsche', kategorie: 'Obst',
    saison: ['Sommer'], herkunft: 'Europa',
    aromaprofil: ['süß', 'mandelartig', 'fruchtig', 'leicht-säuerlich'],
    geschmack: { acidity: 3, sweetness: 4, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Schokolade', 'Vanille', 'Amaretto', 'Ente', 'Schwein'],
    beschreibung: 'Süß oder sauer – als Clafoutis, Chutney zu Ente, Sorbet oder mazeriert zu Foie Gras.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Feige', kategorie: 'Obst',
    saison: ['Sommer', 'Herbst'], herkunft: 'Mittelmeer',
    aromaprofil: ['honigartig', 'süß', 'erdnussartig', 'mild-herb'],
    geschmack: { acidity: 1, sweetness: 5, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Prosciutto', 'Gorgonzola', 'Honig', 'Walnuss', 'Rosmarin'],
    beschreibung: 'Süß und üppig – roh mit Käse, karamellisiert zu Fleisch oder als Tarte mit Mandeln.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Granatapfel', kategorie: 'Obst',
    saison: ['Herbst', 'Winter'], herkunft: 'Persien',
    aromaprofil: ['säuerlich', 'süß', 'tanninreich', 'fruchtig'],
    geschmack: { acidity: 4, sweetness: 3, bitterness: 2, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Lammfleisch', 'Tahini', 'Minze', 'Joghurt', 'Walnuss'],
    beschreibung: 'Granatapfelmelasse intensiviert Saucen – Kerne als Garnitur, Saft als Reduktion.',
    lagertemp: '5–8°C', einheit: 'Gramm',
  },
  {
    name: 'Mango', kategorie: 'Obst',
    saison: ['Ganzjährig'], herkunft: 'Südasien',
    aromaprofil: ['tropisch', 'süß', 'fruchtig', 'florals'],
    geschmack: { acidity: 2, sweetness: 5, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Chili', 'Limette', 'Koriander', 'Kokos', 'Garnelen'],
    beschreibung: 'Tropisch-süß – als Sorbet, Brunoise in Ceviche, Chutney oder roh mit Salzflocken und Chili.',
    lagertemp: '12–16°C', einheit: 'Gramm',
  },
  {
    name: 'Passionsfrucht', kategorie: 'Obst',
    saison: ['Ganzjährig'], herkunft: 'Südamerika',
    aromaprofil: ['tropisch', 'intensiv-säuerlich', 'blumig', 'exotisch'],
    geschmack: { acidity: 5, sweetness: 3, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Vanille', 'Kokos', 'Schokolade', 'Mango', 'Joghurt'],
    beschreibung: 'Intensiv-säuerlich mit floraler Tiefe – als Curd, Coulis oder im Dessert für tropischen Akzent.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Blutorange', kategorie: 'Obst',
    saison: ['Winter', 'Frühling'], herkunft: 'Sizilien',
    aromaprofil: ['beerig', 'zitrusfrisch', 'süß-säuerlich', 'blumig'],
    geschmack: { acidity: 4, sweetness: 3, bitterness: 2, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Fenchel', 'Schokolade', 'Vanille', 'Ente', 'Campari'],
    beschreibung: 'Charaktervoller als normale Orange – Saft als Reduktion, Filets als Garnitur, Schale als Zeste.',
    lagertemp: '5–8°C', einheit: 'Gramm',
  },
  {
    name: 'Grapefruit', kategorie: 'Obst',
    saison: ['Winter', 'Frühling'], herkunft: 'Karibik',
    aromaprofil: ['bitter', 'frisch', 'säuerlich', 'zitrusartig'],
    geschmack: { acidity: 4, sweetness: 2, bitterness: 4, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Avocado', 'Krabben', 'Vanille', 'Ingwer', 'Campari'],
    beschreibung: 'Mutige Bitterkeit – als Tartare-Basis, Granita oder konfiert in Sirup für Desserts.',
    lagertemp: '5–10°C', einheit: 'Gramm',
  },
  {
    name: 'Aprikose', kategorie: 'Obst',
    saison: ['Sommer'], herkunft: 'Zentralasien',
    aromaprofil: ['süß', 'fruchtig', 'leicht-herb', 'florals'],
    geschmack: { acidity: 3, sweetness: 4, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Mandel', 'Vanille', 'Lavendel', 'Lamm', 'Pistazien'],
    beschreibung: 'Aromatisch und süß – als Tarte, Chutney zu Lamm oder pochiert mit Lavendel und Mandeln.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── NÜSSE & SAMEN ─────────────────────────────────────────────────────────────
  {
    name: 'Haselnuss', kategorie: 'Nüsse & Samen',
    saison: ['Herbst'], herkunft: 'Europa',
    aromaprofil: ['nussig', 'süß', 'geröstet', 'ölig'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Schokolade', 'Sellerie', 'Trüffel', 'Fisch', 'Geflügel'],
    beschreibung: 'Geröstet besonders aromatisch – als Praline, Haselnussöl, Crumble oder ganze Garnitur.',
    lagertemp: '8–15°C', einheit: 'Gramm',
  },
  {
    name: 'Walnuss', kategorie: 'Nüsse & Samen',
    saison: ['Herbst'], herkunft: 'Persien',
    aromaprofil: ['bitter', 'erdig', 'ölig', 'tanninreich'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 3, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Käse', 'Birne', 'Honig', 'Chicorée', 'Roquefort'],
    beschreibung: 'Charaktervolle Bitterkeit – als Öl, Crumble, im Salat oder karamellisiert als Dessert-Element.',
    lagertemp: '8–15°C', einheit: 'Gramm',
  },
  {
    name: 'Pistazie', kategorie: 'Nüsse & Samen',
    saison: ['Ganzjährig'], herkunft: 'Iran',
    aromaprofil: ['süß', 'nussig', 'grün', 'leicht-blumig'],
    geschmack: { acidity: 0, sweetness: 3, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Lamm', 'Aprikose', 'Schokolade', 'Honig', 'Lavendel'],
    beschreibung: 'Intensiv grün und süß-nussig – als Praline, Pesto, Crumble oder Eis unverzichtbar.',
    lagertemp: '8–15°C', einheit: 'Gramm',
  },
  {
    name: 'Mandel', kategorie: 'Nüsse & Samen',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['mild', 'süß', 'nussig', 'leicht-bitterlich'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Kirsche', 'Aprikose', 'Schokolade', 'Marzipan', 'Fisch'],
    beschreibung: 'Vielseitig – geröstet, gemahlen als Praline, blanchiert als Garnitur, als Mandelöl oder -milch.',
    lagertemp: '8–15°C', einheit: 'Gramm',
  },
  {
    name: 'Pinienkern', kategorie: 'Nüsse & Samen',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['mild', 'buttig', 'süß', 'leicht-harzartig'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Basilikum', 'Rosinen', 'Spinat', 'Sardellen', 'Lamm'],
    beschreibung: 'Basis des klassischen Pesto – leicht geröstet mit Honig oder in Agrodolce-Saucen.',
    lagertemp: '8–12°C', einheit: 'Gramm',
  },
  {
    name: 'Sesam', kategorie: 'Nüsse & Samen',
    saison: ['Ganzjährig'], herkunft: 'Afrika / Asien',
    aromaprofil: ['nussig', 'geröstet', 'ölig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 1, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Sojasauce', 'Ingwer', 'Knoblauch', 'Tahini', 'Honig'],
    beschreibung: 'Weiß mild, schwarz intensiver – als Öl, Paste (Tahini), Panierung oder Garnitur.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Kürbiskern', kategorie: 'Nüsse & Samen',
    saison: ['Herbst', 'Winter'], herkunft: 'Mittelamerika',
    aromaprofil: ['nussig', 'ölig', 'mild-herb'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 2, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Kürbis', 'Käse', 'Rote Bete', 'Kürbiskernöl', 'Apfel'],
    beschreibung: 'Knusprige Textur und nussiger Charakter – als Garnitur, in Pesto oder geröstet auf Suppen.',
    lagertemp: '8–15°C', einheit: 'Gramm',
  },

  // ── MILCHPRODUKTE & KÄSE ──────────────────────────────────────────────────────
  {
    name: 'Burrata', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Apulien, Italien',
    aromaprofil: ['cremig', 'milchig', 'frisch', 'mild'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 2, spiciness: 0, saltiness: 1 },
    pairings: ['Tomate', 'Basilikum', 'Trüffel', 'Prosciutto', 'Olivenöl'],
    beschreibung: 'Cremige Innenmasse trifft feste Mozzarella-Hülle – sofort servieren, nur mit Qualitäts-Zutaten.',
    lagertemp: '4–6°C', einheit: 'Gramm',
  },
  {
    name: 'Mozzarella', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Kampanien, Italien',
    aromaprofil: ['mild', 'milchig', 'frisch', 'leicht-säuerlich'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 0, umami: 2, spiciness: 0, saltiness: 1 },
    pairings: ['Tomate', 'Basilikum', 'Olivenöl', 'Prosciutto', 'Balsamico'],
    beschreibung: 'Frischer Büffelmozzarella bei Zimmertemperatur servieren – mit Salz, Olivenöl und Basilikum.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Parmesan', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Emilia-Romagna, Italien',
    aromaprofil: ['nussig', 'salzig', 'intensiv-umami', 'kristallin'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 1, umami: 5, spiciness: 0, saltiness: 4 },
    pairings: ['Pasta', 'Risotto', 'Trüffel', 'Balsamico', 'Spargel'],
    beschreibung: 'Der Umami-Gipfel unter den Käsen – gerieben, gespänt oder als Schaum in Saucen unverzichtbar.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Pecorino', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Sardinien / Toskana',
    aromaprofil: ['scharf', 'salzig', 'würzig', 'intensiv'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 1, umami: 4, spiciness: 1, saltiness: 4 },
    pairings: ['Pasta', 'Bohnen', 'Honig', 'Birne', 'Walnuss'],
    beschreibung: 'Schärfer als Parmesan – jung mit Honig und Birne, alt als Reibe-Käse für rustikale Pasta.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Comté', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Franche-Comté, Frankreich',
    aromaprofil: ['nussig', 'fruchtig', 'mild-würzig', 'karamellisch'],
    geschmack: { acidity: 2, sweetness: 2, bitterness: 0, umami: 4, spiciness: 0, saltiness: 2 },
    pairings: ['Wein', 'Apfel', 'Walnuss', 'Trüffel', 'Schinken'],
    beschreibung: 'Komplex und lang gereift – als Käsekurs, geschmolzen in Fondues oder gespänt auf Salate.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Ricotta', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Italien',
    aromaprofil: ['mild', 'cremig', 'frisch', 'milchig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 1, spiciness: 0, saltiness: 1 },
    pairings: ['Spinat', 'Zitrone', 'Honig', 'Nüsse', 'Pasta'],
    beschreibung: 'Mild und vielseitig – als Fülle für Ravioli, mit Honig und Nüssen oder in süßen Tarten.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Crème fraîche', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Frankreich',
    aromaprofil: ['cremig', 'leicht-säuerlich', 'mild', 'buttig'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 0, umami: 1, spiciness: 0, saltiness: 1 },
    pairings: ['Kaviar', 'Lachs', 'Kräuter', 'Blini', 'Beeren'],
    beschreibung: 'Dicker als Sahne, stabiler beim Erhitzen – als Sauce-Basis, auf Blini oder als Dipbegleitung.',
    lagertemp: '0–4°C', einheit: 'Milliliter',
  },
  {
    name: 'Mascarpone', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Lombardei, Italien',
    aromaprofil: ['reichhaltig', 'cremig', 'mild', 'buttig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Espresso', 'Kakao', 'Beeren', 'Trüffel', 'Parmesan'],
    beschreibung: 'Reichhaltig und streichfähig – Basis für Tiramisu, als Saucen-Verlängerung oder Meerrettich-Creme.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Butter', kategorie: 'Milchprodukte & Käse',
    saison: ['Ganzjährig'], herkunft: 'Europa',
    aromaprofil: ['buttig', 'cremig', 'mild', 'süßlich'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Kräuter', 'Trüffel', 'Kaviar', 'Fisch', 'Gemüse'],
    beschreibung: 'Montiert in Saucen, braun als Beurre noisette oder klar als Butteröl – unverzichtbare Basis.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── GETREIDE & TEIGWAREN ───────────────────────────────────────────────────────
  {
    name: 'Quinoa', kategorie: 'Getreide & Hülsenfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Südamerika',
    aromaprofil: ['nussig', 'erdnussartig', 'neutral'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Gemüse', 'Kräuter', 'Zitrone', 'Avocado', 'Lachs'],
    beschreibung: 'Proteinreiches Pseudogetreide – als Salat-Basis, gepufft als Textur oder in Patties.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Buchweizen', kategorie: 'Getreide & Hülsenfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Zentralasien',
    aromaprofil: ['erdig', 'nussig', 'herb', 'leicht-bitter'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Pilze', 'Wild', 'Blini', 'Honig', 'Crème fraîche'],
    beschreibung: 'Glutenfrei und charaktervoll – als Blini, Kasha (geröstet) oder Buchweizennudeln (Soba).',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Polenta', kategorie: 'Getreide & Hülsenfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Norditalien',
    aromaprofil: ['mild', 'maisartig', 'buttig (gekocht)'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Pilze', 'Käse', 'Wurst', 'Trüffel', 'Wild'],
    beschreibung: 'Weich und cremig oder fest und gebraten – universelle Beilage der norditalienischen Küche.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Risottoreis', kategorie: 'Getreide & Hülsenfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Norditalien',
    aromaprofil: ['stärkehaltig', 'cremig', 'neutral'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Parmesan', 'Trüffel', 'Meeresfrüchte', 'Wein', 'Butter'],
    beschreibung: 'Arborio oder Carnaroli – gibt Stärke ab, wird cremig ohne Sahne. Mantecatura mit Butter ist Pflicht.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Panko', kategorie: 'Getreide & Hülsenfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Japan',
    aromaprofil: ['neutral', 'leicht-röstartig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Fisch', 'Meeresfrüchte', 'Gemüse', 'Fleisch', 'Kräuter'],
    beschreibung: 'Lockere japanische Semmelbrösel – knuspriger als normale Panierung, ideal für Tonkatsu.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },

  // ── GEWÜRZE KLASSISCH ─────────────────────────────────────────────────────────
  {
    name: 'Zimt', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Sri Lanka',
    aromaprofil: ['warm', 'süß', 'würzig', 'holzig'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 0, spiciness: 2, saltiness: 0 },
    pairings: ['Apfel', 'Schokolade', 'Lamm', 'Lebkuchen', 'Quitte'],
    beschreibung: 'Ceylon-Zimt feiner als Cassia – in süßen und herzhaften Gerichten, in Brühen und Ras el Hanout.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Kardamom', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Indien',
    aromaprofil: ['blumig', 'zitrusartig', 'warm', 'würzig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 0, spiciness: 2, saltiness: 0 },
    pairings: ['Kaffee', 'Schokolade', 'Ingwer', 'Mango', 'Lamm'],
    beschreibung: 'Königin der Gewürze – grüne Kapsel frisch mahlen. In Kaffeegerichten, Desserts und Ras el Hanout.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Sternanis', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'China',
    aromaprofil: ['anisartig', 'süß', 'warm', 'intensiv'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 0, spiciness: 1, saltiness: 0 },
    pairings: ['Ente', 'Schwein', 'Pho-Brühe', 'Birne', 'Schokolade'],
    beschreibung: 'Basis von Pho und 5-Spice – intensiv, daher sparsam einsetzen. Ganz in Brühen, gemahlen in Würzungen.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Kreuzkümmel', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Mittlerer Osten',
    aromaprofil: ['erdig', 'warm', 'nussig', 'würzig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 1, umami: 1, spiciness: 2, saltiness: 0 },
    pairings: ['Lammfleisch', 'Kichererbsen', 'Karotte', 'Joghurt', 'Harissa'],
    beschreibung: 'Geröstet und frisch gemahlen aromatischer – Basis für Hummus, Curry und nordafrikanische Gewürze.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Kurkuma', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Indien',
    aromaprofil: ['erdig', 'leicht-bitter', 'warm', 'pfeffrig'],
    geschmack: { acidity: 0, sweetness: 0, bitterness: 2, umami: 1, spiciness: 1, saltiness: 0 },
    pairings: ['Blumenkohl', 'Linsen', 'Kokosmilch', 'Ingwer', 'Pfeffer'],
    beschreibung: 'Leuchtend gelb – färbt und würzt. Frisch als Rhizom aromatischer als getrocknet.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Geräucherter Paprika', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Spanien (Extremadura)',
    aromaprofil: ['rauchig', 'süß', 'intensiv', 'würzig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 1, umami: 2, spiciness: 1, saltiness: 0 },
    pairings: ['Chorizo', 'Fisch', 'Kartoffel', 'Ei', 'Mayonnaise'],
    beschreibung: 'Pimentón de la Vera – mild oder scharf, gibt tiefen Rauchcharakter ohne Feuer.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Vanille', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Madagaskar',
    aromaprofil: ['süß', 'blumig', 'warm', 'cremig'],
    geschmack: { acidity: 0, sweetness: 3, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Schokolade', 'Beeren', 'Karamell', 'Sahne', 'Hummer'],
    beschreibung: 'Schote auskratzen, dann Schote in Sahne ziehen lassen. Bourbon-Vanille süßer, Tahiti blumiger.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Rosmarin', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['harzig', 'holzig', 'würzig', 'kampferartig'],
    geschmack: { acidity: 0, sweetness: 0, bitterness: 2, umami: 1, spiciness: 1, saltiness: 0 },
    pairings: ['Lamm', 'Kartoffel', 'Olivenöl', 'Knoblauch', 'Schokolade'],
    beschreibung: 'Kräftig und harzartig – mit Maß einsetzen. Sparsam in Ölen infusiert, in Karamell überraschend.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Thymian', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['aromatisch', 'würzig', 'leicht-herb', 'warm'],
    geschmack: { acidity: 0, sweetness: 0, bitterness: 1, umami: 2, spiciness: 1, saltiness: 0 },
    pairings: ['Fleisch', 'Fisch', 'Geflügel', 'Pilze', 'Tomaten'],
    beschreibung: 'Universalkraut der klassischen Küche – in Fonds, Marinaden, Bouquet garni und Kräuterbutter.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Basilikum', kategorie: 'Kräuter & Gewürze',
    saison: ['Sommer'], herkunft: 'Mittelmeer',
    aromaprofil: ['frisch', 'süß', 'anisartig', 'blumig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 1, spiciness: 1, saltiness: 0 },
    pairings: ['Tomate', 'Mozzarella', 'Zitrone', 'Olivenöl', 'Erdbeere'],
    beschreibung: 'Nie kochen – roh oder kurz am Ende. Genoveser Basilikum für Pesto, Thai-Basilikum für Asia.',
    lagertemp: '18–22°C', einheit: 'Gramm',
  },
  {
    name: 'Petersilie', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['frisch', 'grasig', 'leicht-bitter', 'grün'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 2, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Knoblauch', 'Zitrone', 'Olivenöl', 'Fleisch', 'Fisch'],
    beschreibung: 'Glatte Petersilie aromatischer als krause – als Gremolata, Persillade oder Finishing-Kraut.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Schnittlauch', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['mild', 'zwiebelartig', 'frisch'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 1, spiciness: 1, saltiness: 0 },
    pairings: ['Ei', 'Crème fraîche', 'Kartoffel', 'Kaviar', 'Fisch'],
    beschreibung: 'Delikates Finishing-Kraut – roh in feine Röllchen schneiden, nie kochen, auf Crème fraîche.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Minze', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst'], herkunft: 'Mittelmeer',
    aromaprofil: ['frisch', 'kühl', 'mentholartig', 'süß'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 0, spiciness: 1, saltiness: 0 },
    pairings: ['Lamm', 'Joghurt', 'Erbse', 'Wassermelone', 'Schokolade'],
    beschreibung: 'Spearmint milder, Pfefferminze intensiver – roh als Garnitur, als Öl in Desserts oder Raita.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── ASIATISCHE GRUNDLAGEN ─────────────────────────────────────────────────────
  {
    name: 'Dashi', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'Japan',
    aromaprofil: ['umami', 'meeresartig', 'rauchig', 'tief'],
    geschmack: { acidity: 0, sweetness: 0, bitterness: 0, umami: 5, spiciness: 0, saltiness: 2 },
    pairings: ['Miso', 'Tofu', 'Nudeln', 'Gemüse', 'Fisch'],
    beschreibung: 'Grundstock der japanischen Küche aus Kombu und Katsuobushi – Basis für Suppen und Saucen.',
    lagertemp: '0–4°C', einheit: 'Milliliter',
  },
  {
    name: 'Mirin', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'Japan',
    aromaprofil: ['süß', 'mild-alkoholisch', 'karamellisch'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Sojasauce', 'Sake', 'Teriyaki', 'Fisch', 'Geflügel'],
    beschreibung: 'Süßer Reiswein – gibt Gerichten Glanz und rundet Schärfe ab. Basis für Teriyaki-Glasur.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Sojasauce', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'China',
    aromaprofil: ['salzig', 'umami', 'fermentiert', 'komplex'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 1, umami: 5, spiciness: 0, saltiness: 5 },
    pairings: ['Ingwer', 'Sesam', 'Knoblauch', 'Fleisch', 'Tofu'],
    beschreibung: 'Tamari glutenfrei und voller, Koikuchi Standard, Shoyu milder – Umami-Booster aller Küchen.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Kokosmilch', kategorie: 'Öle & Fette',
    saison: ['Ganzjährig'], herkunft: 'Südostasien',
    aromaprofil: ['süß', 'tropisch', 'cremig', 'mild'],
    geschmack: { acidity: 0, sweetness: 3, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Chili', 'Ingwer', 'Koriander', 'Lemongrass', 'Garnelen'],
    beschreibung: 'Vollfett cremig, leicht wässrig – Basis für Curries, Desserts und Soufflés in der Asia-Küche.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Lemongrass', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Südostasien',
    aromaprofil: ['zitronig', 'frisch', 'grasig', 'florals'],
    geschmack: { acidity: 2, sweetness: 0, bitterness: 1, umami: 0, spiciness: 1, saltiness: 0 },
    pairings: ['Garnelen', 'Kokosmilch', 'Ingwer', 'Chili', 'Galangal'],
    beschreibung: 'Weicher innerer Teil fein geschnitten oder ganzer Stängel in Brühen und Currys – nicht mitessen.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Kaffirlimette', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Südostasien',
    aromaprofil: ['zitronig', 'blumig', 'intensiv', 'frisch'],
    geschmack: { acidity: 3, sweetness: 0, bitterness: 2, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Kokosmilch', 'Garnelen', 'Curry', 'Lemongrass', 'Tom Yum'],
    beschreibung: 'Blätter frisch oder getrocknet in Currys und Suppen – Schale für Thai-Paste und Marinaden.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Wakame', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'Japan',
    aromaprofil: ['meeresartig', 'umami', 'leicht-süß', 'jodhaltig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 4, spiciness: 0, saltiness: 3 },
    pairings: ['Miso', 'Tofu', 'Sesam', 'Sojasauce', 'Gurke'],
    beschreibung: 'Grüne Meeresalge – in Misosuppe, Salaten und als Bett für Ceviche oder Fisch.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Katsuobushi', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'Japan',
    aromaprofil: ['rauchig', 'umami', 'fischig', 'intensiv'],
    geschmack: { acidity: 0, sweetness: 0, bitterness: 0, umami: 5, spiciness: 0, saltiness: 3 },
    pairings: ['Dashi', 'Sojasauce', 'Tofu', 'Okonomiyaki', 'Reis'],
    beschreibung: 'Getrockneter fermentierter Bonito – Basis für Dashi, als Garnitur auf Okonomiyaki.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },

  // ── MEDITERRAN & NAHOST ───────────────────────────────────────────────────────
  {
    name: 'Tahini', kategorie: 'Öle & Fette',
    saison: ['Ganzjährig'], herkunft: 'Naher Osten',
    aromaprofil: ['nussig', 'sesam', 'leicht-bitter', 'cremig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 3, spiciness: 0, saltiness: 1 },
    pairings: ['Kichererbsen', 'Knoblauch', 'Zitrone', 'Falafel', 'Aubergine'],
    beschreibung: 'Sesammus – Basis für Hummus, Baba Ganoush und als Dressing mit Zitrone und Knoblauch.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Harissa', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Tunesien',
    aromaprofil: ['scharf', 'rauchig', 'würzig', 'fruchtig'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 1, umami: 2, spiciness: 5, saltiness: 2 },
    pairings: ['Lamm', 'Fisch', 'Hühnchen', 'Joghurt', 'Couscous'],
    beschreibung: 'Nordafrikanische Chili-Paste – scharf und komplex, als Marinade, Dip oder Saucen-Basis.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Ras el Hanout', kategorie: 'Kräuter & Gewürze',
    saison: ['Ganzjährig'], herkunft: 'Marokko',
    aromaprofil: ['warm', 'komplex', 'blumig', 'würzig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 1, umami: 1, spiciness: 2, saltiness: 0 },
    pairings: ['Lamm', 'Hühnchen', 'Couscous', 'Aprikose', 'Mandel'],
    beschreibung: 'Marokkanische Gewürzmischung mit bis zu 35 Zutaten – für Tajine, Couscous und Marinaden.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Kapern', kategorie: 'Fermentiertes',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['salzig', 'säuerlich', 'würzig', 'intensiv'],
    geschmack: { acidity: 4, sweetness: 0, bitterness: 2, umami: 3, spiciness: 0, saltiness: 4 },
    pairings: ['Sardellen', 'Thunfisch', 'Zitrone', 'Butter', 'Lachs'],
    beschreibung: 'Salzige Säure-Bombe – in Salz eingelegt besser als in Essig. Vor Verwendung spülen.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Sardellen', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Mittelmeer',
    aromaprofil: ['intensiv', 'salzig', 'umami', 'fischig'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 0, umami: 5, spiciness: 0, saltiness: 5 },
    pairings: ['Kapern', 'Tomate', 'Olivenöl', 'Knoblauch', 'Pasta'],
    beschreibung: 'In Öl oder Salz – in Saucen aufgelöst unsichtbar aber tief. Nicht als Fischbeilage, als Würzmittel.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Chorizo', kategorie: 'Fleisch',
    saison: ['Ganzjährig'], herkunft: 'Spanien',
    aromaprofil: ['rauchig', 'würzig', 'scharf', 'intensiv'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 4, spiciness: 3, saltiness: 4 },
    pairings: ['Ei', 'Kartoffel', 'Paprika', 'Kichererbsen', 'Muscheln'],
    beschreibung: 'Geräuchert oder roh – gibt Öl rote Farbe und Paprikaschärfe ab, ideal für Socarrat.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Bottarga', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Ganzjährig'], herkunft: 'Sardinien / Sizilien',
    aromaprofil: ['intensiv', 'salzig', 'umami', 'meeresartig'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 1, umami: 5, spiciness: 0, saltiness: 5 },
    pairings: ['Pasta', 'Zucchini', 'Zitrone', 'Olivenöl', 'Butter'],
    beschreibung: 'Gepresster, getrockneter Rogen von Meeräsche – fein gerieben auf Pasta oder Carpaccio.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
];

export async function POST(req: NextRequest) {
  const user = await getRequestUser(req);
  if (!user || user.email !== ADMIN_EMAIL) {
    return NextResponse.json({ error: 'Nicht autorisiert. Diese Aktion ist nur für Admins.' }, { status: 403 });
  }
  const supabase = createAdminClient();

  const { data, error } = await supabase
    .from('zutaten')
    .insert(MEHR_ZUTATEN)
    .select('id, name');

  if (error) {
    console.error('[seed-mehr-zutaten] insert failed:', error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, count: data.length, inserted: data.map((r: { id: number; name: string }) => r.name) });
}
