import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase-admin';
import { getRequestUser } from '@/lib/get-request-user';
import { ADMIN_EMAIL } from '@/config/roles';

const ZUTATEN = [
  // ── GEMÜSE ──────────────────────────────────────────────────────────────────
  {
    name: 'Weißer Spargel', kategorie: 'Gemüse',
    saison: ['Frühling'], herkunft: 'Deutschland',
    aromaprofil: ['nussig', 'zart', 'mild', 'frisch'],
    geschmack: { acidity: 2, sweetness: 3, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Sauce Hollandaise', 'Morcheln', 'Schinken', 'Butterschaum', 'Trüffel'],
    beschreibung: 'Der König des deutschen Gemüses. Zart und nussig, perfekt für klassische und moderne Fine-Dining-Gerichte.',
    lagertemp: '2–4°C', einheit: 'Gramm',
  },
  {
    name: 'Schwarzwurzel', kategorie: 'Gemüse',
    saison: ['Winter'], herkunft: 'Europa',
    aromaprofil: ['erdig', 'nussig', 'milchig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 1, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Trüffel', 'Wildgeflügel', 'Haselnuss', 'Beurre noisette'],
    beschreibung: 'Das "schwarze Gold" des Winters – unterschätztes Wintergemüse mit tiefem, nussigem Charakter.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Topinambur', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['nussig', 'erdig', 'artischockenartig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Jakobsmuschel', 'Foie Gras', 'Haselnuss', 'Trüffel', 'Lardo'],
    beschreibung: 'Vielseitige Knolle mit artischockenartigem Charakter – als Pürée, Chip, oder Suppe ideal.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Rote Bete', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['erdig', 'süß', 'mineralisch'],
    geschmack: { acidity: 2, sweetness: 4, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Ziegenkäse', 'Meerrettich', 'Orange', 'Walnuss', 'Taubenbrust'],
    beschreibung: 'Tief-erdig und natürlich süß. Als Pürée, Gelee oder roh mariniert ein Klassiker der modernen Küche.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Fenchel', kategorie: 'Gemüse',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Mittelmeer',
    aromaprofil: ['anisartig', 'frisch', 'süß', 'blumig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Meeresfrüchte', 'Steinbutt', 'Orange', 'Pastis', 'Loup de Mer'],
    beschreibung: 'Anisfrischer Charakter, roh und gegart komplett verschieden. Essenziell in der mediterranen Fine-Dining-Küche.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Artischocke', kategorie: 'Gemüse',
    saison: ['Frühling', 'Sommer'], herkunft: 'Mittelmeer',
    aromaprofil: ['bitter', 'nussig', 'erdig', 'artischockenartig'],
    geschmack: { acidity: 2, sweetness: 2, bitterness: 3, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Foie Gras', 'Trüffel', 'Parmesan', 'Bottarga', 'Jakobsmuschel'],
    beschreibung: 'Komplex-bitterer Charakter der jede Weinbegleitung beeinflusst. Vielseitig als Barigoule, Chips oder Creme.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Hokkaido Kürbis', kategorie: 'Gemüse',
    saison: ['Herbst'], herkunft: 'Japan',
    aromaprofil: ['nussig', 'süß', 'cremig', 'butterig'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Ingwer', 'Miso', 'Ras el Hanout', 'Ziegenfrischkäse', 'Shiitake'],
    beschreibung: 'Schale mitessbar, intensiv süß-nussig. Ideal für Veloutés, Pürées und herbstliche Kompositionen.',
    lagertemp: '10–15°C', einheit: 'Gramm',
  },
  {
    name: 'Pak Choi', kategorie: 'Gemüse',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'China',
    aromaprofil: ['mild', 'frisch', 'leicht bitter'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 2, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Ingwer', 'Sesam', 'Austern-Sauce', 'Wagyu', 'Lachs'],
    beschreibung: 'Mild-frischer Blatt- und Stielkohl aus Asien. Kurz gebraten oder gedämpft ideal für asiatisch-europäische Fusionsküche.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Romanesco', kategorie: 'Gemüse',
    saison: ['Herbst', 'Winter'], herkunft: 'Italien',
    aromaprofil: ['nussig', 'mild', 'leicht süß'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Bottarga', 'Anchovis', 'Parmigiano', 'Mandel', 'Trüffel'],
    beschreibung: 'Fraktal-geometrischer Kohl mit mildem, nussigem Aroma. Optisch außergewöhnlich auf dem Teller.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Steckrübe', kategorie: 'Gemüse',
    saison: ['Winter'], herkunft: 'Nordeuropa',
    aromaprofil: ['erdig', 'süß', 'mild', 'würzig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Wildschwein', 'Räucheraal', 'Butter', 'Thymian', 'Miso'],
    beschreibung: 'Unterschätztes Wintergemüse mit tiefer Süße. In der New Nordic Cuisine längst rehabilitiert.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── FLEISCH ─────────────────────────────────────────────────────────────────
  {
    name: 'Kalbsbäckchen', kategorie: 'Fleisch',
    saison: ['Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['intensiv', 'gelatinös', 'tief', 'fleischig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 1 },
    pairings: ['Morcheln', 'Vin Jaune', 'Polenta', 'Gremolata', 'Rote Bete'],
    beschreibung: 'Geschmorte Kalbsbäckchen – kollagenreich, tief aromatisch. Einer der intensivsten Cuts für das Fine Dining Schmorgericht.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Lammrücken', kategorie: 'Fleisch',
    saison: ['Frühling'], herkunft: 'Europa',
    aromaprofil: ['intensiv', 'wild', 'leicht gamig', 'kräuterig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 4, spiciness: 0, saltiness: 1 },
    pairings: ['Bärlauch', 'Artischocke', 'Rosmarin', 'Jus d\'Agneau', 'Erbse'],
    beschreibung: 'Zarter Rücken vom Frühlingslamm – klassisches Fine-Dining-Stück mit mildem, charakteristischem Aroma.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Entenbrust', kategorie: 'Fleisch',
    saison: ['Herbst', 'Winter'], herkunft: 'Frankreich',
    aromaprofil: ['reich', 'fettig', 'intensiv', 'wild'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 4, spiciness: 0, saltiness: 1 },
    pairings: ['Orange', 'Kirschen', 'Trüffel', 'Rotkohl', 'Pflaume'],
    beschreibung: 'Magret de Canard – reich und intensiv, ideal rare bis medium-rare mit knuspriger Haut serviert.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Taubenbrust', kategorie: 'Fleisch',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Frankreich',
    aromaprofil: ['wild', 'intensiv', 'zart', 'leicht leberisch'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 1 },
    pairings: ['Rote Bete', 'Pistazien', 'Foie Gras', 'Pinot Noir-Jus', 'Schwarze Johannisbeere'],
    beschreibung: 'Das eleganteste Wildgeflügel – intensiv, zart, perfekt saignant. Königlich in der Fine Dining Küche.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Kalbsleber', kategorie: 'Fleisch',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['metallisch', 'intensiv', 'cremig', 'reich'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 5, spiciness: 0, saltiness: 1 },
    pairings: ['Apfel', 'Kapern', 'Salbei', 'Bacon', 'Zwiebel-Confit'],
    beschreibung: 'Feinste Schlachtnebenprodukte – zart und cremig wenn frisch und nur kurz angebraten.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Ibérico Secreto', kategorie: 'Fleisch',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Spanien',
    aromaprofil: ['nussig', 'fettig', 'intensiv', 'bellota'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 5, spiciness: 0, saltiness: 1 },
    pairings: ['Manchego', 'Piquillos', 'Sherry', 'Romesco', 'Membrillo'],
    beschreibung: 'Der versteckte Schnitt des Iberischen Schweins – außergewöhnlich marmoriert mit Eichelmast-Aromen.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Wagyu Beef', kategorie: 'Fleisch',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['butterig', 'süß', 'intensiv', 'nussig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Wasabi', 'Ponzu', 'Trüffel', 'Miso', 'Gänselebermousse'],
    beschreibung: 'Ultimative Marmorierung – das fetteste und geschmacksintensivste Rindfleisch der Welt. Weniger ist mehr.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Schwarzfederhuhn', kategorie: 'Fleisch',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Frankreich',
    aromaprofil: ['mild', 'zart', 'fein', 'elegant'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Morcheln', 'Vin Jaune', 'Trüffel', 'Estragon', 'Butterjus'],
    beschreibung: 'Poulet de Bresse AOC – das Edelste der Geflügelwelt. Zartes, charaktervolles Fleisch für klassische Haute Cuisine.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },

  // ── FISCH & MEERESFRÜCHTE ───────────────────────────────────────────────────
  {
    name: 'Steinbutt', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Nordsee',
    aromaprofil: ['mild', 'fest', 'delikat', 'meeresfrisch'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 4, spiciness: 0, saltiness: 1 },
    pairings: ['Beurre Blanc', 'Kaviar', 'Champagner-Sauce', 'Trüffel', 'Rucola'],
    beschreibung: 'Der König der Plattfische – festes, weißes Fleisch mit delikater Textur und mildem Geschmack.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Jakobsmuschel', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Herbst', 'Winter', 'Frühling'], herkunft: 'Atlantik',
    aromaprofil: ['süß', 'zart', 'meeresfrisch', 'nussig'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 0, umami: 4, spiciness: 0, saltiness: 1 },
    pairings: ['Blumenkohl', 'Topinambur', 'Kaviar', 'Nussbutter', 'Rote Bete'],
    beschreibung: 'Coquilles Saint-Jacques – natürliche Süße und zarte Textur machen sie zum Lieblings-Meeresfrüchte im Fine Dining.',
    lagertemp: '0–2°C', einheit: 'Stück',
  },
  {
    name: 'Loup de Mer', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Mittelmeer',
    aromaprofil: ['mild', 'zart', 'delikat', 'salzig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 3, spiciness: 0, saltiness: 1 },
    pairings: ['Fenchel', 'Pastis', 'Provence-Kräuter', 'Olivenöl', 'Tomate'],
    beschreibung: 'Wolfsbarsch – der elegante Mittelmeerfisch, klassisch im Salzmantel oder auf der Haut gebraten.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Kabeljau', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Winter', 'Frühling'], herkunft: 'Nordatlantik',
    aromaprofil: ['mild', 'fest', 'leicht süß'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 3, spiciness: 0, saltiness: 1 },
    pairings: ['Kartoffel', 'Aioli', 'Chorizo', 'Erbse', 'Brandade'],
    beschreibung: 'Vielseitiger Nordatlantik-Fisch – konfiert, pochiert oder sous-vide zubereitet ein Klassiker.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Langustine', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Frühling', 'Sommer'], herkunft: 'Atlantik',
    aromaprofil: ['süß', 'zart', 'intensiv', 'meeresfrisch'],
    geschmack: { acidity: 1, sweetness: 4, bitterness: 0, umami: 4, spiciness: 0, saltiness: 2 },
    pairings: ['Bisque', 'Safran', 'Kaviar', 'Butter-Nage', 'Gurke'],
    beschreibung: 'Kaisergranat – Scampi der Spitzenklasse. Zart, süßlich, perfekt kurz gegart oder roh als Tatar.',
    lagertemp: '0–1°C', einheit: 'Stück',
  },
  {
    name: 'Auster', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Herbst', 'Winter'], herkunft: 'Atlantik',
    aromaprofil: ['mineralisch', 'salzig', 'meeresfrisch', 'jodisch'],
    geschmack: { acidity: 2, sweetness: 1, bitterness: 0, umami: 4, spiciness: 0, saltiness: 3 },
    pairings: ['Champagner', 'Zitrone', 'Mignonette', 'Wakame', 'Rote-Bete-Granité'],
    beschreibung: 'Terroir des Meeres – jede Auster spiegelt ihren Herkunftsort. Roh der reinste Ausdruck von Meeresfrüchten.',
    lagertemp: '4–8°C', einheit: 'Stück',
  },
  {
    name: 'Seeigel (Uni)', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Winter'], herkunft: 'Japan',
    aromaprofil: ['jodisch', 'cremig', 'intensiv', 'meeresartig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 5, spiciness: 0, saltiness: 2 },
    pairings: ['Pasta', 'Jakobsmuschel', 'Kaviar', 'Crème fraîche', 'Dashi'],
    beschreibung: 'Uni – das cremigste und umami-reichste Meeresprodukt. Wenige Gramm genügen für einen intensiven Effekt.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Forelle', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['mild', 'zart', 'leicht nussig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Mandel', 'Kapern', 'Dill', 'Crème fraîche', 'Rote Bete'],
    beschreibung: 'Regenbogen- oder Bachforelle – klar und mild, ideal für Beizen, Pochieren oder klassisch Meunière.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Hamachi', kategorie: 'Fisch & Meeresfrüchte',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['butterig', 'mild', 'reich', 'leicht süß'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 4, spiciness: 0, saltiness: 1 },
    pairings: ['Yuzu', 'Jalapeño', 'Ponzu', 'Sesam', 'Wakame'],
    beschreibung: 'Japanische Gelbschwanzmakrele – reich und butterig, hervorragend als Sashimi oder lecker mariniert.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },

  // ── PILZE ────────────────────────────────────────────────────────────────────
  {
    name: 'Morchel', kategorie: 'Pilze',
    saison: ['Frühling'], herkunft: 'Europa',
    aromaprofil: ['erdig', 'nussig', 'intensiv', 'rauchig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Spargel', 'Vin Jaune', 'Schwarzfederhuhn', 'Rahmsauce', 'Eigelb'],
    beschreibung: 'Die erste Delikatesse des Frühlings – intensiv-erdig, tief aromatisch. Nur trocken oder gekocht verwenden.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Schwarze Trüffel', kategorie: 'Pilze',
    saison: ['Winter'], herkunft: 'Frankreich',
    aromaprofil: ['erdig', 'moschusartig', 'intensiv', 'komplex'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Foie Gras', 'Eigelb', 'Sellerie', 'Rinderfilet', 'Artischocke'],
    beschreibung: 'Périgord-Trüffel – das schwarze Diamant der Küche. Intensiv-erdig mit komplexem Aromaprofil.',
    lagertemp: '2–4°C', einheit: 'Gramm',
  },
  {
    name: 'Weiße Trüffel', kategorie: 'Pilze',
    saison: ['Herbst'], herkunft: 'Italien',
    aromaprofil: ['knoblauchartig', 'erdig', 'intensiv', 'honigig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Tagliolini', 'Risotto', 'Eigelb', 'Fonduta', 'Jakobsmuschel'],
    beschreibung: 'Alba-Trüffel – der teuerste und aromatischste Pilz der Welt. Ausschließlich roh über Gerichte hobeln.',
    lagertemp: '2–4°C', einheit: 'Gramm',
  },
  {
    name: 'Pfifferling', kategorie: 'Pilze',
    saison: ['Sommer', 'Herbst'], herkunft: 'Europa',
    aromaprofil: ['fruchtig', 'pfeffrig', 'nussig', 'erdig'],
    geschmack: { acidity: 2, sweetness: 2, bitterness: 0, umami: 4, spiciness: 1, saltiness: 0 },
    pairings: ['Ei', 'Petersilie', 'Speck', 'Kalbfleisch', 'Crème fraîche'],
    beschreibung: 'Cantharellus cibarius – der beliebteste Wildpilz Europas. Fruchtig-pfeffrig mit gold-gelber Farbe.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Steinpilz', kategorie: 'Pilze',
    saison: ['Herbst'], herkunft: 'Europa',
    aromaprofil: ['nussig', 'erdig', 'intensiv', 'waldige'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Risotto', 'Tagliatelle', 'Rinderfilet', 'Parmesan', 'Salbei'],
    beschreibung: 'Porcini – der Klassiker unter den Edelpilzen. Getrocknet noch intensiver, frisch unvergleichlich.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Shiitake', kategorie: 'Pilze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['rauchig', 'erdig', 'intensiv', 'umami-reich'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 5, spiciness: 0, saltiness: 0 },
    pairings: ['Miso', 'Soja', 'Wagyu', 'Dashi', 'Pak Choi'],
    beschreibung: 'Lentinula edodes – das Rückgrat der japanischen Küche. Reich an natürlichem Glutamat, Basis für Dashi.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Matsutake', kategorie: 'Pilze',
    saison: ['Herbst'], herkunft: 'Japan',
    aromaprofil: ['würzig', 'kiefernartig', 'komplex', 'aromatisch'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 4, spiciness: 0, saltiness: 0 },
    pairings: ['Reis', 'Dashi', 'Sake', 'Jakobsmuschel', 'Yuzu'],
    beschreibung: 'Der teuerste japanische Pilz – unverwechselbar aromatisch mit Kiefernwald-Charakter.',
    lagertemp: '0–2°C', einheit: 'Gramm',
  },
  {
    name: 'Enoki', kategorie: 'Pilze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['mild', 'leicht fruchtig', 'zart'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Sukiyaki', 'Miso-Suppe', 'Hotpot', 'Steinbutt', 'Dashi'],
    beschreibung: 'Zarte Fadenpilze mit eleganter Optik. Roh oder kurz gebraten für texturalen Kontrast.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── KRÄUTER & GEWÜRZE ────────────────────────────────────────────────────────
  {
    name: 'Bärlauch', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling'], herkunft: 'Europa',
    aromaprofil: ['knoblauchartig', 'frisch', 'intensiv', 'grün'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 0, umami: 2, spiciness: 1, saltiness: 0 },
    pairings: ['Lammrücken', 'Ricotta', 'Jakobsmuschel', 'Burrata', 'Pasta'],
    beschreibung: 'Allium ursinum – das Knoblauch-Kraut des Frühlings. Nie kochen, nur kurz erwärmen oder roh einsetzen.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Liebstöckel', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['intensiv', 'sellerieartig', 'würzig', 'herbal'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 3, spiciness: 1, saltiness: 0 },
    pairings: ['Hummer-Bisque', 'Tomatensuppe', 'Kalbsfond', 'Fisch-Consommé'],
    beschreibung: 'Maggi-Kraut – sparsam eingesetzt, extrem intensiv. Natürlicher Umami-Verstärker in Fonds und Saucen.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Estragon', kategorie: 'Kräuter & Gewürze',
    saison: ['Sommer'], herkunft: 'Frankreich',
    aromaprofil: ['anisartig', 'frisch', 'intensiv', 'blumig'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Bernaise', 'Hühnchen', 'Hummer', 'Senf', 'Sauce Gribiche'],
    beschreibung: 'Das Anis-Kraut der klassischen französischen Küche – unersetzlich für Béarnaise und Fines Herbes.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Kerbelknolle', kategorie: 'Kräuter & Gewürze',
    saison: ['Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['anis', 'nussig', 'süßlich', 'komplex'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Trüffel', 'Steinbutt', 'Jakobsmuschel', 'Langustine', 'Butter'],
    beschreibung: 'Die Knolle des Garten-Kerbels – süß-anisartig, zart. Im Sous-vide oder als Pürée ein Winterschatz.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Shiso', kategorie: 'Kräuter & Gewürze',
    saison: ['Sommer'], herkunft: 'Japan',
    aromaprofil: ['minzig', 'anisartig', 'frisch', 'zitrusartig'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Hamachi', 'Auster', 'Sashimi', 'Sesam', 'Ponzu'],
    beschreibung: 'Japanisches Basilikum in Rot und Grün – frisch-aromatisch, unverzichtbar in der japanischen Fine Cuisine.',
    lagertemp: '8–10°C', einheit: 'Gramm',
  },
  {
    name: 'Szechuan Pfeffer', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'China',
    aromaprofil: ['zitrusartig', 'betäubend', 'scharf', 'blumig'],
    geschmack: { acidity: 2, sweetness: 0, bitterness: 1, umami: 0, spiciness: 4, saltiness: 0 },
    pairings: ['Entenbrust', 'Schokolade', 'Jakobsmuschel', 'Sake', 'Öl-Infusion'],
    beschreibung: 'Zanthoxylum – numbing spice aus Sichuan. Betäubende Schärfe und Zitrusaroma, ein faszinierender Fine-Dining-Twist.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Safran', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Iran',
    aromaprofil: ['blumig', 'honigartig', 'metallisch', 'komplex'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 1, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Risotto', 'Bouillabaisse', 'Langustine', 'Panna cotta', 'Muscheln'],
    beschreibung: 'Crocus sativus – das teuerste Gewürz der Welt. Sparsam eingesetzt, intensiv und unvergesslich.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Tonkabohne', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Südamerika',
    aromaprofil: ['vanilleartig', 'süß', 'nussig', 'mandel'],
    geschmack: { acidity: 0, sweetness: 4, bitterness: 2, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Schokolade', 'Erdbeere', 'Foie Gras', 'Crème brûlée', 'Whisky'],
    beschreibung: 'Dipteryx odorata – Vanille-Alternative mit Coumarin-Tiefe. Maßvoll gerieben über Desserts unvergesslich.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Sumac', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Nahost',
    aromaprofil: ['säuerlich', 'fruchtig', 'herb', 'tanninhaltig'],
    geschmack: { acidity: 5, sweetness: 0, bitterness: 1, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Lammfleisch', 'Hummus', 'Za\'atar', 'Joghurt', 'Rote Zwiebel'],
    beschreibung: 'Rhus coriaria – fruchtige Säure aus der Levante. Als Ersatz für Zitronensäure mit fruchtiger Tiefe.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Sancho Pfeffer', kategorie: 'Kräuter & Gewürze',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['zitrusartig', 'frisch', 'leicht scharf', 'grün'],
    geschmack: { acidity: 3, sweetness: 0, bitterness: 0, umami: 0, spiciness: 3, saltiness: 0 },
    pairings: ['Aal', 'Miso-Suppe', 'Ramen', 'Jakobsmuschel', 'Yuzu'],
    beschreibung: 'Japanische Variante des Szechuan Pfeffers – frischer, zitrusartiger mit weniger betäubendem Effekt.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },

  // ── FERMENTIERTES & UMAMI ───────────────────────────────────────────────────
  {
    name: 'Shio Koji', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['salzig', 'süß', 'umami-reich', 'mild fermentiert'],
    geschmack: { acidity: 1, sweetness: 2, bitterness: 0, umami: 5, spiciness: 0, saltiness: 3 },
    pairings: ['Steinbutt', 'Rinderfilet', 'Hühnchen', 'Jakobsmuschel', 'Gemüse'],
    beschreibung: 'Salz-Koji-Marinade – enzymatisch aktiv, zartert Proteine und verstärkt Umami. 24h Marinade für Fleisch und Fisch.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Miso Shiro', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['mild', 'süß', 'umami', 'leicht fermentiert'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 4, spiciness: 0, saltiness: 2 },
    pairings: ['Butterkaramell', 'Aubergine', 'Lachs', 'Crème fraîche', 'Haselnuss'],
    beschreibung: 'Weißes Miso – mild und süß, kurz fermentiert. Vielseitig in Saucen, Desserts und Marinaden.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Miso Mugi', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['intensiv', 'salzig', 'erdig', 'tief fermentiert'],
    geschmack: { acidity: 1, sweetness: 1, bitterness: 2, umami: 5, spiciness: 0, saltiness: 3 },
    pairings: ['Ramen-Brühe', 'Marinaden', 'Aubergine', 'Rindfleisch', 'Schokolade'],
    beschreibung: 'Dunkles Gerstenmiso – intensiv und salzig, lange fermentiert. Tiefe Umami-Basis für Saucen und Jus.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Garum', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Nordeuropa',
    aromaprofil: ['intensiv', 'salzig', 'komplex', 'tief umami'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 0, umami: 5, spiciness: 0, saltiness: 5 },
    pairings: ['Fleischsaucen', 'Pasta', 'Dressings', 'Butter-Emulsionen'],
    beschreibung: 'Fermentierte Fisch- oder Fleischsauce – das Colatura di Alici der Noma-Küche. Extreme Umami-Konzentration.',
    lagertemp: '0–4°C', einheit: 'Milliliter',
  },
  {
    name: 'Kombu', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['meeresartig', 'umami', 'salzig', 'mineral'],
    geschmack: { acidity: 1, sweetness: 0, bitterness: 0, umami: 5, spiciness: 0, saltiness: 2 },
    pairings: ['Dashi', 'Miso-Suppe', 'Nabe', 'Ponzu', 'Fischfond'],
    beschreibung: 'Saccharina japonica – Grundlage des Dashi und ultimativer Glutamat-Träger. Basis der japanischen Küche.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },
  {
    name: 'Yuzu Kosho', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Japan',
    aromaprofil: ['scharf', 'zitrusartig', 'salzig', 'fermentiert'],
    geschmack: { acidity: 4, sweetness: 0, bitterness: 0, umami: 2, spiciness: 4, saltiness: 3 },
    pairings: ['Wagyu', 'Jakobsmuschel', 'Hamachi', 'Hühnchen', 'Auster'],
    beschreibung: 'Fermentierte Yuzu-Chili-Paste – explosiv und komplex. Nur wenige Gramm genügen für maximale Wirkung.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Gochujang', kategorie: 'Fermentiertes',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Korea',
    aromaprofil: ['scharf', 'süß', 'fermentiert', 'rauchig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 4, spiciness: 4, saltiness: 2 },
    pairings: ['Rindfleisch', 'Bulgogi', 'Bibimbap', 'Ente', 'Karamell'],
    beschreibung: 'Koreanische Gochujang – fermentierte Chilipaste mit Tiefe und Süße, weit jenseits einfacher Schärfe.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },

  // ── SÄUREN & FRISCHE ────────────────────────────────────────────────────────
  {
    name: 'Verjus', kategorie: 'Obst',
    saison: ['Sommer', 'Herbst'], herkunft: 'Frankreich',
    aromaprofil: ['säuerlich', 'fruchtig', 'mild', 'weinig'],
    geschmack: { acidity: 4, sweetness: 2, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Foie Gras', 'Kalb', 'Vinaigretten', 'Beurre blanc', 'Fischgerichte'],
    beschreibung: 'Saft unreifer Trauben – mildere, fruchtiger Säureersatz für Wein in der Küche. Weinbegleitung-freundlich.',
    lagertemp: '0–4°C', einheit: 'Milliliter',
  },
  {
    name: 'Yuzu', kategorie: 'Obst',
    saison: ['Winter'], herkunft: 'Japan',
    aromaprofil: ['intensiv sauer', 'blumig', 'komplex', 'zitrusartig'],
    geschmack: { acidity: 5, sweetness: 1, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Jakobsmuschel', 'Hamachi', 'Crème brûlée', 'Sake', 'Weiße Schokolade'],
    beschreibung: 'Citrus junos – die aromatischste Zitrusfrucht. Saft und Schale extrem intensiv, sparsamster Einsatz nötig.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Sudachi', kategorie: 'Obst',
    saison: ['Sommer', 'Herbst'], herkunft: 'Japan',
    aromaprofil: ['säuerlich', 'frisch', 'zitrusartig', 'grün'],
    geschmack: { acidity: 4, sweetness: 1, bitterness: 1, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Matsutake', 'Sashimi', 'Nabe', 'Sake', 'Grüner Tee'],
    beschreibung: 'Kleine grüne japanische Zitrusfrucht – frischer und grüner als Yuzu, ideal als aromatischer Finish.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Meyer Zitrone', kategorie: 'Obst',
    saison: ['Winter', 'Frühling'], herkunft: 'USA',
    aromaprofil: ['mild sauer', 'blumig', 'süß', 'zitrusartig'],
    geschmack: { acidity: 3, sweetness: 3, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Fisch', 'Hummer', 'Tarte au citron', 'Ricotta', 'Engelshaarkuchen'],
    beschreibung: 'Kreuzung aus Zitrone und Mandarine – süßer und komplexer als normale Zitronen, ideal für Desserts.',
    lagertemp: '4–8°C', einheit: 'Gramm',
  },
  {
    name: 'Holunderblüte', kategorie: 'Obst',
    saison: ['Frühling', 'Sommer'], herkunft: 'Europa',
    aromaprofil: ['blumig', 'süß', 'frisch', 'muskatartig'],
    geschmack: { acidity: 1, sweetness: 3, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Erdbeere', 'Rhabarber', 'Ziegenkäse', 'Crème fraîche', 'Champagner'],
    beschreibung: 'Sambucus nigra – kurze Saison, intensives Aroma. Als Sirup, Gelee oder frisch über Desserts.',
    lagertemp: '0–4°C', einheit: 'Gramm',
  },
  {
    name: 'Tamarinde', kategorie: 'Obst',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Indien',
    aromaprofil: ['säuerlich', 'süß', 'fruchtig', 'dattelartig'],
    geschmack: { acidity: 4, sweetness: 3, bitterness: 0, umami: 1, spiciness: 0, saltiness: 0 },
    pairings: ['Entenbrust', 'Hähnchen', 'Chutney', 'Pad Thai', 'Rote Bete'],
    beschreibung: 'Tamarindus indica – tropische Säure mit Datteln-Tiefe. Ideal für Glasuren, Chutneys und asiatische Saucen.',
    lagertemp: '15–20°C', einheit: 'Gramm',
  },

  // ── ÖLE & FETTE ─────────────────────────────────────────────────────────────
  {
    name: 'Haselnussöl', kategorie: 'Öle & Fette',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['nussig', 'intensiv', 'warm', 'röstartig'],
    geschmack: { acidity: 0, sweetness: 2, bitterness: 0, umami: 2, spiciness: 0, saltiness: 0 },
    pairings: ['Jakobsmuschel', 'Rote Bete', 'Schokolade', 'Fenchel', 'Vinaigrette'],
    beschreibung: 'Intensivstes Nussöl Europas – kaltgepresst unvergesslich als Finish und in Vinaigretten.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Arganöl', kategorie: 'Öle & Fette',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Marokko',
    aromaprofil: ['nussig', 'erdig', 'intensiv', 'leicht rauchig'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Couscous', 'Lamm', 'Tajine', 'Honig', 'Mandeln'],
    beschreibung: 'Flüssiges Gold Marokkos – geröstet intensiv-nussig, kalt sanfter. Ideal für nordafrikanische Fine-Dining-Interpretationen.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Traubenkernöl', kategorie: 'Öle & Fette',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Europa',
    aromaprofil: ['mild', 'leicht fruchtig', 'neutral'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 0, spiciness: 0, saltiness: 0 },
    pairings: ['Mayonnaise', 'Salatdressings', 'Emulsionen', 'Frittiertes'],
    beschreibung: 'Höchster Rauchpunkt unter den Qualitätsölen – ideal für Emulsionen und neutrale Anwendungen.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
  {
    name: 'Sesamöl', kategorie: 'Öle & Fette',
    saison: ['Frühling', 'Sommer', 'Herbst', 'Winter'], herkunft: 'Asien',
    aromaprofil: ['nussig', 'intensiv', 'röstartig', 'warm'],
    geschmack: { acidity: 0, sweetness: 1, bitterness: 0, umami: 3, spiciness: 0, saltiness: 0 },
    pairings: ['Wok-Gerichte', 'Miso', 'Sashimi', 'Pak Choi', 'Ramen'],
    beschreibung: 'Dunkles geröstetes Sesamöl – nur als Finish verwenden, nie erhitzen. Intensivster Geschmacksträger der asiatischen Küche.',
    lagertemp: '15–20°C', einheit: 'Milliliter',
  },
];

export async function POST(req: NextRequest) {
  const user = await getRequestUser(req);
  if (!user || user.email !== ADMIN_EMAIL) {
    return NextResponse.json({ error: 'Nicht autorisiert. Diese Aktion ist nur für Admins.' }, { status: 403 });
  }
  const supabase = createAdminClient();

  const { error: delError } = await supabase.from('zutaten').delete().neq('id', 0);
  if (delError) {
    console.error('[seed-zutaten] delete failed:', delError.message);
    return NextResponse.json({ error: delError.message }, { status: 500 });
  }

  const { data, error } = await supabase
    .from('zutaten')
    .insert(ZUTATEN)
    .select('id, name');

  if (error) {
    console.error('[seed-zutaten] insert failed:', error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ ok: true, count: data.length, inserted: data.map(r => r.name) });
}
